
#import <Foundation/Foundation.h>
#import <ThingSmartUtil/ThingSmartUtil.h>

/// PTZ direction enumeration
typedef NS_ENUM(NSUInteger, ThingSmartPTZControlDirection) {
    ThingSmartPTZControlDirectionUp = 0,
    ThingSmartPTZControlDirectionRightUp,
    ThingSmartPTZControlDirectionRight,
    ThingSmartPTZControlDirectionRightDown,
    ThingSmartPTZControlDirectionDown,
    ThingSmartPTZControlDirectionLeftDown,
    ThingSmartPTZControlDirectionLeft,
    ThingSmartPTZControlDirectionLeftUp
};

/// Cruise mode enumeration
typedef NS_ENUM(NSUInteger, ThingSmartPTZControlCruiseMode) {
    ThingSmartPTZControlCruiseModePanoramic = 0,// Panoramic cruise
    ThingSmartPTZControlCruiseModeCollectionPoint // Collection point cruise
};

/// Cruise time mode enumeration
typedef NS_ENUM(NSUInteger, ThingSmartPTZControlCruiseTimeMode) {
    ThingSmartPTZControlCruiseTimeModeAllDay = 0,// Full day cruise
    ThingSmartPTZControlCruiseTimeModeCustom // Custom time cruise
};

/// Cruise status enumeration
typedef NS_ENUM(NSUInteger, ThingSmartPTZControlCruiseState) {
    ThingSmartPTZControlCruiseStatePanoramic = 0,// Panoramic cruising
    ThingSmartPTZControlCruiseStateCollectionPoint,// Collection point cruising
    ThingSmartPTZControlCruiseStateNone // Not in cruising
};

NS_ASSUME_NONNULL_BEGIN

/// Collection point model
@interface ThingCameraCollectionPointModel : NSObject
/// Device id
@property (nonatomic, strong) NSString *devId;
/// Collection point id
@property (nonatomic, strong) NSString *pointId;
/// Unique id in the device, generated by the device
@property (nonatomic, strong) NSString *mpId;
/// Collection point name
@property (nonatomic, strong) NSString *name;
/// The address of the picture
@property (nonatomic, strong) NSString *pic;
/// Collection point location information
@property (nonatomic, strong) NSString *pos;
/// Picture decryption key
@property (nonatomic, strong) NSString *encryption;

/// Generate a collection point model array
/// @param dictArray Collection point diction array
+ (NSArray *)modelsWithDictArray:(NSArray *)dictArray;

@end

NS_ASSUME_NONNULL_END

NS_ASSUME_NONNULL_BEGIN

@class ThingSmartPTZManager;
@protocol ThingSmartPTZManagerDeletate <NSObject>

@optional

/// Did execute collectionPoint action
/// @param manager PTZ management class
/// @param type value:1, add collectionPoint; 2, remove collectionPoint; 3、 jump to specific collectionPoint
- (void)collectionPointAction:(ThingSmartPTZManager *)manager actionType:(NSInteger)type;

/// Cruise switch state changed
/// @param manager PTZ management class
/// @param isOpen Cruise switch open state, YES, is opened; NO, is closed
- (void)didUpdateCruiseSwitchState:(ThingSmartPTZManager *)manager isOpen:(BOOL)isOpen;

/// Cruise mode changed
/// @param manager PTZ management class
/// @param currentCruiseMode Current cruise mode. ThingSmartPTZControlCruiseModePanoramic, panoramic mode; ThingSmartPTZControlCruiseModeCollectionPoint, collectionPoint mode
- (void)didUpdateCruiseMode:(ThingSmartPTZManager *)manager currentCruiseMode:(ThingSmartPTZControlCruiseMode)currentCruiseMode;

/// Cruise time mode changed
/// @param manager PTZ management class
/// @param currentTimeMode The current cruise time mode. Value is a ThingSmartPTZControlCruiseTimeMode enum.
- (void)didUpdateCruiseTimeMode:(ThingSmartPTZManager *)manager currentTimeMode:(ThingSmartPTZControlCruiseTimeMode)currentTimeMode;

/// Cruise time mode - Cruise time updated
/// @param manager PTZ management class
/// @param startTime The time to start cruising. Format:"HH:mm"
/// @param endTime The time to end cruising.Format:"HH:mm"
- (void)didUpdateCruiseTimeModeTime:(ThingSmartPTZManager *)manager startTime:(NSString *)startTime endTime:(NSString *)endTime;

/// The switch state of mobile tracking has changed
/// @param manager PTZ management class
/// @param isOpen The latest value of open state
- (void)didUpdateMotionTrackingState:(ThingSmartPTZManager *)manager isOpen:(BOOL)isOpen;

@end

NS_ASSUME_NONNULL_END

NS_ASSUME_NONNULL_BEGIN

@interface ThingSmartPTZManager : NSObject

@property (nonatomic, weak) id<ThingSmartPTZManagerDeletate> delegate;

/// Initialization
/// @param devId Device id
- (instancetype)initWithDeviceId:(NSString *)devId;

/// Is support PTZ control
- (BOOL)isSupportPTZControl;

/// Get all supported directions
/// Eg, ["0","1","2","3","4","5","6","7"]
- (NSArray *)requestSupportedPTZControlDirections;

/// Start PTZ control
/// @param direction Direction enumeration
/// @param success Successful callback
/// @param failure Failed callback
/// error.code, 8，Already reached the limit；9，It is being calibrated, please wait
- (void)startPTZWithDirection:(ThingSmartPTZControlDirection)direction
         success:(ThingSuccessID)success
         failure:(ThingFailureError)failure;

/// Stop PTZ control
/// @param success Successful callback
/// @param failure Failed callback
- (void)stopPTZWithSuccess:(ThingSuccessID)success
                   failure:(ThingFailureError)failure;


/// Is support zoom action
- (BOOL)isSupportZoomAction;

/// Start zooming
/// @param isEnlarge YES，Get bigger；NO，Get smaller
/// @param success Successful callback
/// @param failure Failed callback
- (void)startPTZZoomWithIsEnlarge:(BOOL)isEnlarge
         success:(ThingSuccessID)success
         failure:(ThingFailureError)failure;

/// Stop zooming
/// @param success Successful callback
/// @param failure Failed callback
- (void)stopZoomActionWithSuccess:(ThingSuccessID)success
                          failure:(ThingFailureError)failure;


/// Is support collection point
- (BOOL)isSupportCollectionPoint;

/// Could operate collection point.
/// Only in non-cruise mode, can operate collection point
- (BOOL)couldOperateCollectionPoint;

/// Get collection points
/// @param success Successful callback
/// In the list is some ThingCameraCollectionPointModels
/// @param failure Failed callback
- (void)requestCollectionPointListWithSuccess:(ThingSuccessList)success failure:(ThingFailureError)failure;

/// Add collection point
/// @param name Collection point name
/// @param success Successful callback
/// @param failure Failed callback
- (void)addCollectionPointWithName:(NSString *)name success:(ThingSuccessHandler)success failure:(ThingFailureError)failure;

/// Delete collection points
/// @param models The collection point model array you want to remove
/// @param success Successful callback
/// @param failure Failed callback
- (void)deleteCollectionPoints:(NSArray<ThingCameraCollectionPointModel *> *)models success:(ThingSuccessHandler)success failure:(ThingFailureError)failure;

/// Modify collection point name
/// @param model Collection point model
/// @param name New name
/// @param success Successful callback
/// @param failure Failed callback
- (void)renameCollectionPoint:(ThingCameraCollectionPointModel *)model name:(NSString *)name success:(ThingSuccessHandler)success failure:(ThingFailureError)failure;

/// View collection point
/// @param model Collection point model
/// @param success Successful callback
/// @param failure Failed callback
- (void)viewCollectionPoint:(ThingCameraCollectionPointModel *)model success:(ThingSuccessHandler)success failure:(ThingFailureError)failure;

/// Is support cruise
- (BOOL)isSupportCruise;

/// Get current cruise open state
- (BOOL)isOpenCruise;

/// Get current cruise mode
/// 0, Panoramic cruise; 1, Preset point cruise
- (ThingSmartPTZControlCruiseMode)getCurrentCruiseMode;

/// Get current cruise time mode
/// 0, Full day cruise; 1, Custom time cruise
- (ThingSmartPTZControlCruiseTimeMode)getCurrentCruiseTimeMode;

/// Get current cruise state
/// 0，Panoramic cruising；1，Collection point cruising；2，Not in cruising
- (ThingSmartPTZControlCruiseState)getCurrentCruiseState;

/// Get current cruise time
/// Format：startTime-endTime，eg, "09:00-18:00"
- (NSString *)getCurrentCruiseTime;

/// Open or close cruise switch
/// @param isOpen YES，open；NO，close
/// @param success Successful callback
/// @param failure Failed callback
- (void)setCruiseOpen:(BOOL)isOpen success:(ThingSuccessID)success failure:(ThingFailureError)failure;

/// Set cruise mode
/// @param mode Cruise mode, 0, Panoramic cruise; 1, Preset point cruise
/// @param success Successful callback
/// @param failure Failed callback
- (void)setCruiseMode:(ThingSmartPTZControlCruiseMode)mode success:(ThingSuccessID)success failure:(ThingFailureError)failure;

/// Set cruise time mode
/// @param timeMode Cruise time mode，0、Full day cruise; 1、Custom time cruise
/// @param success Successful callback
/// @param failure Failed callback
- (void)setCruiseTimeMode:(ThingSmartPTZControlCruiseTimeMode)timeMode success:(ThingSuccessHandler)success failure:(ThingFailureError)failure;

/// Set cruise state
/// @param state cruise state，0, Panoramic cruise; 1, Collection point cruise; 2, Not in cruise
/// @param success Successful callback
/// @param failure Failed callback
- (void)setCruiseState:(ThingSmartPTZControlCruiseState)state success:(ThingSuccessHandler)success failure:(ThingFailureError)failure;

/// Set custom time for cruise
/// @param startTime Format "00:00"
/// @param endTime Format "00:00"
/// @param success Successful callback
/// @param failure Failed callback
- (void)setCruiseCustomWithStartTime:(NSString *)startTime endTime:(NSString *)endTime success:(ThingSuccessHandler)success failure:(ThingFailureError)failure;

/// Is support motionTracking
- (BOOL)isSupportMotionTracking;

/// Is open motionTracking
- (BOOL)isOpenMotionTracking;

/// Open or close motionTracking
/// @param isOpen YES，open action；NO，is close action
/// @param success Successful callback
/// @param failure Failed callback
- (void)setMotionTrackingState:(BOOL)isOpen success:(ThingSuccessHandler)success failure:(ThingFailureError)failure;

/// Is support preset point
- (BOOL)isSupportPresetPoint;

/// Get preset points, eg, ["1","2","3","4"]
- (NSArray *)requestSupportedPresetPoints;

/// View the preset point at Index
/// @param index Enumeration value of preset point, which is get from requestSupportedPresetPoints api
/// @param success Successful callback
/// @param failure Failed callback
- (void)viewPresetPointWithIndex:(NSInteger)index success:(ThingSuccessID)success failure:(ThingFailureError)failure;

/// Set the preset point at index
/// @param index Enumeration value of preset point, which is get from requestSupportedPresetPoints api
/// @param success Successful callback
/// @param failure Failed callback
- (void)setPresetPointWithIndex:(NSInteger)index success:(ThingSuccessID)success failure:(ThingFailureError)failure;

@end

NS_ASSUME_NONNULL_END
