#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
#ifndef INDUSTRYACTIVATORKIT_SWIFT_H
#define INDUSTRYACTIVATORKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="IndustryActivatorKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// The basic activator params. your should not use this class directly, use the sub class instead.
SWIFT_CLASS("_TtC20IndustryActivatorKit15ActivatorParams")
@interface ActivatorParams : NSObject
@property (nonatomic) NSTimeInterval timeOut;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;

SWIFT_CLASS("_TtC20IndustryActivatorKit17APActivatorParams")
@interface APActivatorParams : ActivatorParams
@property (nonatomic, copy) NSString * _Nonnull ssid;
@property (nonatomic, copy) NSString * _Nonnull password;
@property (nonatomic, copy) NSString * _Nonnull pairToken;
- (nonnull instancetype)initWithSsid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password token:(NSString * _Nonnull)token timeOut:(NSTimeInterval)timeOut OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithSsid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password token:(NSString * _Nonnull)token OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ActivatorError, open) {
  ActivatorErrorPairFailure = 13001,
  ActivatorErrorQrCodeError = 13002,
  ActivatorErrorTimeOutError = 13003,
};

typedef SWIFT_ENUM(NSInteger, ActivatorMode, open) {
  ActivatorModeEZ = 0,
  ActivatorModeAP = 1,
  ActivatorModeWiredGateway = 2,
  ActivatorModeQRCode = 3,
  ActivatorModeZigbeeSubDevice = 4,
  ActivatorModeQRScan = 5,
  ActivatorModeBLE = 6,
  ActivatorModeBLEWIFI = 7,
  ActivatorModeBLEWIFICloud = 8,
};



SWIFT_CLASS("_TtC20IndustryActivatorKit16ActivatorService")
@interface ActivatorService : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) ActivatorService * _Nonnull shared;)
+ (ActivatorService * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(ActivatorService * _Nonnull)value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol IActivator;
@class NSData;

SWIFT_PROTOCOL("_TtP20IndustryActivatorKit17IActivatorService_")
@protocol IActivatorService <NSObject>
- (void)activatorTokenWithAssetId:(NSString * _Nonnull)assetId longitude:(NSString * _Nullable)longitude latitude:(NSString * _Nullable)latitude success:(void (^ _Nullable)(NSString * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
- (id <IActivator> _Nonnull)activator:(enum ActivatorMode)mode SWIFT_WARN_UNUSED_RESULT;
- (NSData * _Nullable)QRCodeDataForQRCodeActivatorModeWithSsid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password pairToken:(NSString * _Nonnull)pairToken SWIFT_WARN_UNUSED_RESULT;
@end


@interface ActivatorService (SWIFT_EXTENSION(IndustryActivatorKit)) <IActivatorService>
- (void)activatorTokenWithAssetId:(NSString * _Nonnull)assetId longitude:(NSString * _Nullable)longitude latitude:(NSString * _Nullable)latitude success:(void (^ _Nullable)(NSString * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
- (id <IActivator> _Nonnull)activator:(enum ActivatorMode)mode SWIFT_WARN_UNUSED_RESULT;
- (NSData * _Nullable)QRCodeDataForQRCodeActivatorModeWithSsid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password pairToken:(NSString * _Nonnull)pairToken SWIFT_WARN_UNUSED_RESULT;
@end

@protocol ISmartBLEAdv;

SWIFT_CLASS("_TtC20IndustryActivatorKit18BLEActivatorParams")
@interface BLEActivatorParams : ActivatorParams
@property (nonatomic, strong) id <ISmartBLEAdv> _Nonnull deviceInfo;
@property (nonatomic, copy) NSString * _Nonnull assetId;
- (nonnull instancetype)initWithDeviceInfo:(id <ISmartBLEAdv> _Nonnull)deviceInfo assetId:(NSString * _Nonnull)assetId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithDeviceInfo:(id <ISmartBLEAdv> _Nonnull)deviceInfo assetId:(NSString * _Nonnull)assetId timeOut:(NSTimeInterval)timeOut OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC20IndustryActivatorKit22BLEWIFIActivatorParams")
@interface BLEWIFIActivatorParams : ActivatorParams
@property (nonatomic, strong) id <ISmartBLEAdv> _Nonnull deviceInfo;
@property (nonatomic, copy) NSString * _Nonnull assetId;
@property (nonatomic, copy) NSString * _Nonnull pairToken;
@property (nonatomic, copy) NSString * _Nonnull ssid;
@property (nonatomic, copy) NSString * _Nonnull password;
@property (nonatomic) BOOL onlyConnectBle;
- (nonnull instancetype)initWithDeviceInfo:(id <ISmartBLEAdv> _Nonnull)deviceInfo assetId:(NSString * _Nonnull)assetId pairToken:(NSString * _Nonnull)pairToken ssid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password onlyConnectBle:(BOOL)onlyConnectBle OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithDeviceInfo:(id <ISmartBLEAdv> _Nonnull)deviceInfo assetId:(NSString * _Nonnull)assetId pairToken:(NSString * _Nonnull)pairToken ssid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password onlyConnectBle:(BOOL)onlyConnectBle timeOut:(NSTimeInterval)timeOut OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC20IndustryActivatorKit27BLEWIFICloudActivatorParams")
@interface BLEWIFICloudActivatorParams : ActivatorParams
@property (nonatomic, copy) NSString * _Nonnull devId;
@property (nonatomic, copy) NSString * _Nonnull ssid;
@property (nonatomic, copy) NSString * _Nonnull password;
- (nonnull instancetype)initWithDevId:(NSString * _Nonnull)devId ssid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithDevId:(NSString * _Nonnull)devId ssid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password timeOut:(NSTimeInterval)timeOut OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, DiscoveryMode, open) {
  DiscoveryModeBLE = 1,
  DiscoveryModeBLEWIFI = 2,
  DiscoveryModeWIRED = 3,
};


SWIFT_CLASS("_TtC20IndustryActivatorKit16DiscoveryService")
@interface DiscoveryService : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) DiscoveryService * _Nonnull shared;)
+ (DiscoveryService * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(DiscoveryService * _Nonnull)value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol IDiscovery;

SWIFT_PROTOCOL("_TtP20IndustryActivatorKit17IDiscoveryService_")
@protocol IDiscoveryService <NSObject>
- (id <IDiscovery> _Nonnull)discovery:(enum DiscoveryMode)mode SWIFT_WARN_UNUSED_RESULT;
@end


@interface DiscoveryService (SWIFT_EXTENSION(IndustryActivatorKit)) <IDiscoveryService>
- (id <IDiscovery> _Nonnull)discovery:(enum DiscoveryMode)mode SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC20IndustryActivatorKit17EZActivatorParams")
@interface EZActivatorParams : ActivatorParams
@property (nonatomic, copy) NSString * _Nonnull ssid;
@property (nonatomic, copy) NSString * _Nonnull password;
@property (nonatomic, copy) NSString * _Nonnull pairToken;
- (nonnull instancetype)initWithSsid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password token:(NSString * _Nonnull)token timeOut:(NSTimeInterval)timeOut OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithSsid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password token:(NSString * _Nonnull)token OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP20IndustryActivatorKit16IActivatedDevice_")
@protocol IActivatedDevice <NSObject>
/// The universally unique identifier of the device.
@property (nonatomic, copy) NSString * _Nonnull uuid;
/// The device ID.
@property (nonatomic, copy) NSString * _Nonnull deviceId;
/// The name of the device.
@property (nonatomic, copy) NSString * _Nonnull name;
/// The product ID.
@property (nonatomic, copy) NSString * _Nonnull productID;
/// The longitude of the device.
@property (nonatomic, copy) NSString * _Nonnull longitude;
/// The latitude of the device.
@property (nonatomic, copy) NSString * _Nonnull latitude;
/// The IP address of the device.
@property (nonatomic, copy) NSString * _Nonnull ipAddress;
/// A boolean value indicates whether the device is online.
@property (nonatomic) BOOL isOnline;
@property (nonatomic, copy) NSString * _Nonnull meshId;
@end

@protocol IActivatorListener;

SWIFT_PROTOCOL("_TtP20IndustryActivatorKit10IActivator_")
@protocol IActivator <NSObject>
@property (nonatomic, weak) id <IActivatorListener> _Nullable listener;
/// use for EZ, AP, WiredGateway, QRCode, QRScan, BLE, BLEWIFI pair
- (void)startPair:(ActivatorParams * _Nonnull)params;
- (void)stopPair;
@end


SWIFT_PROTOCOL("_TtP20IndustryActivatorKit18IActivatorListener_")
@protocol IActivatorListener <NSObject>
- (void)onSuccessWithDeviceModel:(id <IActivatedDevice> _Nullable)deviceModel;
- (void)onErrorWithError:(NSError * _Nonnull)error;
@end


@protocol IDiscoveryListener;

SWIFT_PROTOCOL("_TtP20IndustryActivatorKit10IDiscovery_")
@protocol IDiscovery <NSObject>
@property (nonatomic, weak) id <IDiscoveryListener> _Nullable listener;
- (void)startDiscovery;
- (void)stopDiscovery;
@end


SWIFT_PROTOCOL("_TtP20IndustryActivatorKit18IDiscoveryListener_")
@protocol IDiscoveryListener <NSObject>
@optional
/// did discover a device
/// \param device the device be discovered. it will be kind of ISmartBLEAdv if the mode is ble
///
- (void)didDiscoverWithDevice:(id <ISmartBLEAdv> _Nullable)device;
/// did discover a device
/// \param deviceId the device ID be discovered.
///
/// \param productId the product ID be discivered.
///
- (void)didDiscoverWithDeviceId:(NSString * _Nonnull)deviceId productId:(NSString * _Nonnull)productId;
@end


enum SmartBLEType : NSInteger;

SWIFT_PROTOCOL("_TtP20IndustryActivatorKit12ISmartBLEAdv_")
@protocol ISmartBLEAdv <NSObject>
/// The UUID of the Bluetooth LE device.
@property (nonatomic, copy) NSString * _Nullable uuid;
/// The product ID of the Bluetooth LE device.
@property (nonatomic, copy) NSString * _Nullable productId;
/// The MAC address of the Bluetooth LE device.
@property (nonatomic, copy) NSString * _Nullable mac;
/// The activation state of the Bluetooth LE device.
@property (nonatomic) BOOL isActive;
/// The type of Bluetooth LE device.
@property (nonatomic) enum SmartBLEType bleType;
/// Indicates whether the Bluetooth LE device supports connections through the router on a 5 GHz band.
@property (nonatomic) BOOL isSupport5G;
/// Indicates whether the Bluetooth LE device supports the product key.
@property (nonatomic) BOOL isProuductKey;
/// The protocol version of the Bluetooth LE device.
@property (nonatomic) NSInteger bleProtocolV;
/// Whether the device is activated by scanning, such as scanning a QR code. Defaults to false.
@property (nonatomic) BOOL isQRCodeDevice;
/// Whether the device is support config by multi user.
@property (nonatomic) BOOL isSupportMultiUserShare;
@end


@interface NSError (SWIFT_EXTENSION(IndustryActivatorKit))
+ (NSError * _Nonnull)pairFailure:(NSString * _Nullable)des SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)qrCodeError:(NSString * _Nullable)des SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)timeOutError:(NSString * _Nullable)des SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC20IndustryActivatorKit21QRCodeActivatorParams")
@interface QRCodeActivatorParams : ActivatorParams
@property (nonatomic, copy) NSString * _Nonnull ssid;
@property (nonatomic, copy) NSString * _Nonnull password;
@property (nonatomic, copy) NSString * _Nonnull pairToken;
- (nonnull instancetype)initWithSsid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password token:(NSString * _Nonnull)token timeOut:(NSTimeInterval)timeOut OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithSsid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password token:(NSString * _Nonnull)token OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC20IndustryActivatorKit21QRScanActivatorParams")
@interface QRScanActivatorParams : ActivatorParams
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic, copy) NSString * _Nonnull assetId;
@property (nonatomic, copy) NSString * _Nonnull ssid;
@property (nonatomic, copy) NSString * _Nonnull password;
- (nonnull instancetype)initWithCode:(NSString * _Nonnull)code assetId:(NSString * _Nonnull)assetId ssid:(NSString * _Nullable)ssid password:(NSString * _Nullable)password timeOut:(NSTimeInterval)timeOut OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCode:(NSString * _Nonnull)code assetId:(NSString * _Nonnull)assetId ssid:(NSString * _Nullable)ssid password:(NSString * _Nullable)password OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, SmartBLEType, open) {
/// The unknown type of Bluetooth LE device.
  SmartBLETypeUnknow = 1,
/// The type of Bluetooth LE device that supports an earlier protocol. The device does not support a security protocol.
  SmartBLETypeBle = 2,
/// The type of Bluetooth LE device that supports an earlier protocol of a lower security level.
  SmartBLETypeBlePlus = 3,
/// The type of Bluetooth LE device that supports an earlier protocol. The device does not support a security protocol.
  SmartBLETypeBleWifi = 4,
/// The type of Bluetooth LE device that supports a later protocol of a higher security level.
  SmartBLETypeBleSecurity = 5,
/// The type of Bluetooth LE dual-mode device that supports a later protocol of a higher security level.
  SmartBLETypeBleWifiSecurity = 6,
/// The type of Bluetooth LE dual-mode device that supports a later protocol of a higher security level and that supports the plug and play (PnP) function.
  SmartBLETypeBleWifiPlugPlay = 7,
/// The type of Bluetooth LE and Zigbee dual-mode device that supports a later protocol of a higher security level.
  SmartBLETypeBleZigbee = 8,
/// The type of Bluetooth LE and LTE Category 1 dual-mode device that supports a later protocol of a higher security level.
  SmartBLETypeBleLTESecurity = 9,
/// The beacon security.
  SmartBLETypeBleBeacon = 10,
/// Same as the ThingSmartBLETypeBLEWifiPlugPlay, but BLE is prior while configing.
  SmartBLETypeBleWifiPriorBLE = 11,
};


SWIFT_CLASS("_TtC20IndustryActivatorKit27WiredGatewayActivatorParams")
@interface WiredGatewayActivatorParams : ActivatorParams
@property (nonatomic, copy) NSString * _Nonnull pairToken;
@property (nonatomic, copy) NSString * _Nonnull gwId;
@property (nonatomic, copy) NSString * _Nonnull pid;
- (nonnull instancetype)initWithGwId:(NSString * _Nonnull)gwId productId:(NSString * _Nonnull)productId token:(NSString * _Nonnull)token timeOut:(NSTimeInterval)timeOut OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithGwId:(NSString * _Nonnull)gwId productId:(NSString * _Nonnull)productId token:(NSString * _Nonnull)token OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC20IndustryActivatorKit30ZigbeeSubDeviceActivatorParams")
@interface ZigbeeSubDeviceActivatorParams : ActivatorParams
@property (nonatomic, copy) NSString * _Nonnull gwId;
@property (nonatomic, copy) NSString * _Nonnull localKey;
@property (nonatomic) double pv;
- (nonnull instancetype)initWithGwId:(NSString * _Nonnull)gwId localKey:(NSString * _Nonnull)localKey pv:(double)pv OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithGwId:(NSString * _Nonnull)gwId localKey:(NSString * _Nonnull)localKey pv:(double)pv timeOut:(NSTimeInterval)timeOut OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
#ifndef INDUSTRYACTIVATORKIT_SWIFT_H
#define INDUSTRYACTIVATORKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="IndustryActivatorKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// The basic activator params. your should not use this class directly, use the sub class instead.
SWIFT_CLASS("_TtC20IndustryActivatorKit15ActivatorParams")
@interface ActivatorParams : NSObject
@property (nonatomic) NSTimeInterval timeOut;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;

SWIFT_CLASS("_TtC20IndustryActivatorKit17APActivatorParams")
@interface APActivatorParams : ActivatorParams
@property (nonatomic, copy) NSString * _Nonnull ssid;
@property (nonatomic, copy) NSString * _Nonnull password;
@property (nonatomic, copy) NSString * _Nonnull pairToken;
- (nonnull instancetype)initWithSsid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password token:(NSString * _Nonnull)token timeOut:(NSTimeInterval)timeOut OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithSsid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password token:(NSString * _Nonnull)token OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ActivatorError, open) {
  ActivatorErrorPairFailure = 13001,
  ActivatorErrorQrCodeError = 13002,
  ActivatorErrorTimeOutError = 13003,
};

typedef SWIFT_ENUM(NSInteger, ActivatorMode, open) {
  ActivatorModeEZ = 0,
  ActivatorModeAP = 1,
  ActivatorModeWiredGateway = 2,
  ActivatorModeQRCode = 3,
  ActivatorModeZigbeeSubDevice = 4,
  ActivatorModeQRScan = 5,
  ActivatorModeBLE = 6,
  ActivatorModeBLEWIFI = 7,
  ActivatorModeBLEWIFICloud = 8,
};



SWIFT_CLASS("_TtC20IndustryActivatorKit16ActivatorService")
@interface ActivatorService : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) ActivatorService * _Nonnull shared;)
+ (ActivatorService * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(ActivatorService * _Nonnull)value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol IActivator;
@class NSData;

SWIFT_PROTOCOL("_TtP20IndustryActivatorKit17IActivatorService_")
@protocol IActivatorService <NSObject>
- (void)activatorTokenWithAssetId:(NSString * _Nonnull)assetId longitude:(NSString * _Nullable)longitude latitude:(NSString * _Nullable)latitude success:(void (^ _Nullable)(NSString * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
- (id <IActivator> _Nonnull)activator:(enum ActivatorMode)mode SWIFT_WARN_UNUSED_RESULT;
- (NSData * _Nullable)QRCodeDataForQRCodeActivatorModeWithSsid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password pairToken:(NSString * _Nonnull)pairToken SWIFT_WARN_UNUSED_RESULT;
@end


@interface ActivatorService (SWIFT_EXTENSION(IndustryActivatorKit)) <IActivatorService>
- (void)activatorTokenWithAssetId:(NSString * _Nonnull)assetId longitude:(NSString * _Nullable)longitude latitude:(NSString * _Nullable)latitude success:(void (^ _Nullable)(NSString * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
- (id <IActivator> _Nonnull)activator:(enum ActivatorMode)mode SWIFT_WARN_UNUSED_RESULT;
- (NSData * _Nullable)QRCodeDataForQRCodeActivatorModeWithSsid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password pairToken:(NSString * _Nonnull)pairToken SWIFT_WARN_UNUSED_RESULT;
@end

@protocol ISmartBLEAdv;

SWIFT_CLASS("_TtC20IndustryActivatorKit18BLEActivatorParams")
@interface BLEActivatorParams : ActivatorParams
@property (nonatomic, strong) id <ISmartBLEAdv> _Nonnull deviceInfo;
@property (nonatomic, copy) NSString * _Nonnull assetId;
- (nonnull instancetype)initWithDeviceInfo:(id <ISmartBLEAdv> _Nonnull)deviceInfo assetId:(NSString * _Nonnull)assetId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithDeviceInfo:(id <ISmartBLEAdv> _Nonnull)deviceInfo assetId:(NSString * _Nonnull)assetId timeOut:(NSTimeInterval)timeOut OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC20IndustryActivatorKit22BLEWIFIActivatorParams")
@interface BLEWIFIActivatorParams : ActivatorParams
@property (nonatomic, strong) id <ISmartBLEAdv> _Nonnull deviceInfo;
@property (nonatomic, copy) NSString * _Nonnull assetId;
@property (nonatomic, copy) NSString * _Nonnull pairToken;
@property (nonatomic, copy) NSString * _Nonnull ssid;
@property (nonatomic, copy) NSString * _Nonnull password;
@property (nonatomic) BOOL onlyConnectBle;
- (nonnull instancetype)initWithDeviceInfo:(id <ISmartBLEAdv> _Nonnull)deviceInfo assetId:(NSString * _Nonnull)assetId pairToken:(NSString * _Nonnull)pairToken ssid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password onlyConnectBle:(BOOL)onlyConnectBle OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithDeviceInfo:(id <ISmartBLEAdv> _Nonnull)deviceInfo assetId:(NSString * _Nonnull)assetId pairToken:(NSString * _Nonnull)pairToken ssid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password onlyConnectBle:(BOOL)onlyConnectBle timeOut:(NSTimeInterval)timeOut OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC20IndustryActivatorKit27BLEWIFICloudActivatorParams")
@interface BLEWIFICloudActivatorParams : ActivatorParams
@property (nonatomic, copy) NSString * _Nonnull devId;
@property (nonatomic, copy) NSString * _Nonnull ssid;
@property (nonatomic, copy) NSString * _Nonnull password;
- (nonnull instancetype)initWithDevId:(NSString * _Nonnull)devId ssid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithDevId:(NSString * _Nonnull)devId ssid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password timeOut:(NSTimeInterval)timeOut OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, DiscoveryMode, open) {
  DiscoveryModeBLE = 1,
  DiscoveryModeBLEWIFI = 2,
  DiscoveryModeWIRED = 3,
};


SWIFT_CLASS("_TtC20IndustryActivatorKit16DiscoveryService")
@interface DiscoveryService : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) DiscoveryService * _Nonnull shared;)
+ (DiscoveryService * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(DiscoveryService * _Nonnull)value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol IDiscovery;

SWIFT_PROTOCOL("_TtP20IndustryActivatorKit17IDiscoveryService_")
@protocol IDiscoveryService <NSObject>
- (id <IDiscovery> _Nonnull)discovery:(enum DiscoveryMode)mode SWIFT_WARN_UNUSED_RESULT;
@end


@interface DiscoveryService (SWIFT_EXTENSION(IndustryActivatorKit)) <IDiscoveryService>
- (id <IDiscovery> _Nonnull)discovery:(enum DiscoveryMode)mode SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC20IndustryActivatorKit17EZActivatorParams")
@interface EZActivatorParams : ActivatorParams
@property (nonatomic, copy) NSString * _Nonnull ssid;
@property (nonatomic, copy) NSString * _Nonnull password;
@property (nonatomic, copy) NSString * _Nonnull pairToken;
- (nonnull instancetype)initWithSsid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password token:(NSString * _Nonnull)token timeOut:(NSTimeInterval)timeOut OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithSsid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password token:(NSString * _Nonnull)token OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP20IndustryActivatorKit16IActivatedDevice_")
@protocol IActivatedDevice <NSObject>
/// The universally unique identifier of the device.
@property (nonatomic, copy) NSString * _Nonnull uuid;
/// The device ID.
@property (nonatomic, copy) NSString * _Nonnull deviceId;
/// The name of the device.
@property (nonatomic, copy) NSString * _Nonnull name;
/// The product ID.
@property (nonatomic, copy) NSString * _Nonnull productID;
/// The longitude of the device.
@property (nonatomic, copy) NSString * _Nonnull longitude;
/// The latitude of the device.
@property (nonatomic, copy) NSString * _Nonnull latitude;
/// The IP address of the device.
@property (nonatomic, copy) NSString * _Nonnull ipAddress;
/// A boolean value indicates whether the device is online.
@property (nonatomic) BOOL isOnline;
@property (nonatomic, copy) NSString * _Nonnull meshId;
@end

@protocol IActivatorListener;

SWIFT_PROTOCOL("_TtP20IndustryActivatorKit10IActivator_")
@protocol IActivator <NSObject>
@property (nonatomic, weak) id <IActivatorListener> _Nullable listener;
/// use for EZ, AP, WiredGateway, QRCode, QRScan, BLE, BLEWIFI pair
- (void)startPair:(ActivatorParams * _Nonnull)params;
- (void)stopPair;
@end


SWIFT_PROTOCOL("_TtP20IndustryActivatorKit18IActivatorListener_")
@protocol IActivatorListener <NSObject>
- (void)onSuccessWithDeviceModel:(id <IActivatedDevice> _Nullable)deviceModel;
- (void)onErrorWithError:(NSError * _Nonnull)error;
@end


@protocol IDiscoveryListener;

SWIFT_PROTOCOL("_TtP20IndustryActivatorKit10IDiscovery_")
@protocol IDiscovery <NSObject>
@property (nonatomic, weak) id <IDiscoveryListener> _Nullable listener;
- (void)startDiscovery;
- (void)stopDiscovery;
@end


SWIFT_PROTOCOL("_TtP20IndustryActivatorKit18IDiscoveryListener_")
@protocol IDiscoveryListener <NSObject>
@optional
/// did discover a device
/// \param device the device be discovered. it will be kind of ISmartBLEAdv if the mode is ble
///
- (void)didDiscoverWithDevice:(id <ISmartBLEAdv> _Nullable)device;
/// did discover a device
/// \param deviceId the device ID be discovered.
///
/// \param productId the product ID be discivered.
///
- (void)didDiscoverWithDeviceId:(NSString * _Nonnull)deviceId productId:(NSString * _Nonnull)productId;
@end


enum SmartBLEType : NSInteger;

SWIFT_PROTOCOL("_TtP20IndustryActivatorKit12ISmartBLEAdv_")
@protocol ISmartBLEAdv <NSObject>
/// The UUID of the Bluetooth LE device.
@property (nonatomic, copy) NSString * _Nullable uuid;
/// The product ID of the Bluetooth LE device.
@property (nonatomic, copy) NSString * _Nullable productId;
/// The MAC address of the Bluetooth LE device.
@property (nonatomic, copy) NSString * _Nullable mac;
/// The activation state of the Bluetooth LE device.
@property (nonatomic) BOOL isActive;
/// The type of Bluetooth LE device.
@property (nonatomic) enum SmartBLEType bleType;
/// Indicates whether the Bluetooth LE device supports connections through the router on a 5 GHz band.
@property (nonatomic) BOOL isSupport5G;
/// Indicates whether the Bluetooth LE device supports the product key.
@property (nonatomic) BOOL isProuductKey;
/// The protocol version of the Bluetooth LE device.
@property (nonatomic) NSInteger bleProtocolV;
/// Whether the device is activated by scanning, such as scanning a QR code. Defaults to false.
@property (nonatomic) BOOL isQRCodeDevice;
/// Whether the device is support config by multi user.
@property (nonatomic) BOOL isSupportMultiUserShare;
@end


@interface NSError (SWIFT_EXTENSION(IndustryActivatorKit))
+ (NSError * _Nonnull)pairFailure:(NSString * _Nullable)des SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)qrCodeError:(NSString * _Nullable)des SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)timeOutError:(NSString * _Nullable)des SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC20IndustryActivatorKit21QRCodeActivatorParams")
@interface QRCodeActivatorParams : ActivatorParams
@property (nonatomic, copy) NSString * _Nonnull ssid;
@property (nonatomic, copy) NSString * _Nonnull password;
@property (nonatomic, copy) NSString * _Nonnull pairToken;
- (nonnull instancetype)initWithSsid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password token:(NSString * _Nonnull)token timeOut:(NSTimeInterval)timeOut OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithSsid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password token:(NSString * _Nonnull)token OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC20IndustryActivatorKit21QRScanActivatorParams")
@interface QRScanActivatorParams : ActivatorParams
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic, copy) NSString * _Nonnull assetId;
@property (nonatomic, copy) NSString * _Nonnull ssid;
@property (nonatomic, copy) NSString * _Nonnull password;
- (nonnull instancetype)initWithCode:(NSString * _Nonnull)code assetId:(NSString * _Nonnull)assetId ssid:(NSString * _Nullable)ssid password:(NSString * _Nullable)password timeOut:(NSTimeInterval)timeOut OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCode:(NSString * _Nonnull)code assetId:(NSString * _Nonnull)assetId ssid:(NSString * _Nullable)ssid password:(NSString * _Nullable)password OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, SmartBLEType, open) {
/// The unknown type of Bluetooth LE device.
  SmartBLETypeUnknow = 1,
/// The type of Bluetooth LE device that supports an earlier protocol. The device does not support a security protocol.
  SmartBLETypeBle = 2,
/// The type of Bluetooth LE device that supports an earlier protocol of a lower security level.
  SmartBLETypeBlePlus = 3,
/// The type of Bluetooth LE device that supports an earlier protocol. The device does not support a security protocol.
  SmartBLETypeBleWifi = 4,
/// The type of Bluetooth LE device that supports a later protocol of a higher security level.
  SmartBLETypeBleSecurity = 5,
/// The type of Bluetooth LE dual-mode device that supports a later protocol of a higher security level.
  SmartBLETypeBleWifiSecurity = 6,
/// The type of Bluetooth LE dual-mode device that supports a later protocol of a higher security level and that supports the plug and play (PnP) function.
  SmartBLETypeBleWifiPlugPlay = 7,
/// The type of Bluetooth LE and Zigbee dual-mode device that supports a later protocol of a higher security level.
  SmartBLETypeBleZigbee = 8,
/// The type of Bluetooth LE and LTE Category 1 dual-mode device that supports a later protocol of a higher security level.
  SmartBLETypeBleLTESecurity = 9,
/// The beacon security.
  SmartBLETypeBleBeacon = 10,
/// Same as the ThingSmartBLETypeBLEWifiPlugPlay, but BLE is prior while configing.
  SmartBLETypeBleWifiPriorBLE = 11,
};


SWIFT_CLASS("_TtC20IndustryActivatorKit27WiredGatewayActivatorParams")
@interface WiredGatewayActivatorParams : ActivatorParams
@property (nonatomic, copy) NSString * _Nonnull pairToken;
@property (nonatomic, copy) NSString * _Nonnull gwId;
@property (nonatomic, copy) NSString * _Nonnull pid;
- (nonnull instancetype)initWithGwId:(NSString * _Nonnull)gwId productId:(NSString * _Nonnull)productId token:(NSString * _Nonnull)token timeOut:(NSTimeInterval)timeOut OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithGwId:(NSString * _Nonnull)gwId productId:(NSString * _Nonnull)productId token:(NSString * _Nonnull)token OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC20IndustryActivatorKit30ZigbeeSubDeviceActivatorParams")
@interface ZigbeeSubDeviceActivatorParams : ActivatorParams
@property (nonatomic, copy) NSString * _Nonnull gwId;
@property (nonatomic, copy) NSString * _Nonnull localKey;
@property (nonatomic) double pv;
- (nonnull instancetype)initWithGwId:(NSString * _Nonnull)gwId localKey:(NSString * _Nonnull)localKey pv:(double)pv OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithGwId:(NSString * _Nonnull)gwId localKey:(NSString * _Nonnull)localKey pv:(double)pv timeOut:(NSTimeInterval)timeOut OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
