#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
#ifndef INDUSTRYASSETKIT_SWIFT_H
#define INDUSTRYASSETKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="IndustryAssetKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
typedef SWIFT_ENUM(NSInteger, AssetEvent, open) {
  AssetEventAuth = 0,
  AssetEventUnAuth = 1,
};


SWIFT_CLASS("_TtC16IndustryAssetKit12AssetService")
@interface AssetService : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) AssetService * _Nonnull shared;)
+ (AssetService * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(AssetService * _Nonnull)value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSString;
@protocol IAsset;
@protocol IAssetDeviceListResult;
@protocol IAssetDeviceStatistics;
@protocol IAssociatedModel;
@protocol IAssetMessageService;
@protocol IAssetManager;

SWIFT_PROTOCOL("_TtP16IndustryAssetKit13IAssetService_")
@protocol IAssetService <NSObject>
/// create asset with name
/// \param name the name of the asset to create
///
/// \param parentAssetId the id of the parent asset
///
/// \param success the success callback
///
/// \param failure the failure callback
///
- (void)createWithName:(NSString * _Nonnull)name parentAssetId:(NSString * _Nullable)parentAssetId success:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// update the name of the asset
/// \param assetId the id of the asset to update
///
/// \param name the new name of the asset
///
/// \param success the success callback
///
/// \param failure the failure callback
///
- (void)updateWithAssetId:(NSString * _Nonnull)assetId name:(NSString * _Nonnull)name success:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// remove the asset
/// \param assetId the id of the asset to remove
///
/// \param success the success callback
///
/// \param failure the failure callback
///
- (void)removeWithAssetId:(NSString * _Nonnull)assetId success:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// get the asset detail
/// \param assetId the id of the asset to get
///
/// \param success the success callback
///
/// \param failure the failure callback
///
- (void)assetWithAssetId:(NSString * _Nonnull)assetId success:(void (^ _Nullable)(id <IAsset> _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// get the sub asset list of the asset
/// \param assetId the id of the asset which to get. it means you want to get the top level assets if nil,
///
/// \param success the success callback
///
/// \param failure the failure callback
///
- (void)subAssetsWithAssetId:(NSString * _Nullable)assetId success:(void (^ _Nullable)(NSArray<id <IAsset>> * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// get the device list of the asset
/// \param assetId the id of the asset which you want to get the device list.
///
/// \param lastRowKey the last row key return by last request, or nil if first request
///
/// \param success the success callback
///
/// \param failure the failure callback
///
- (void)devicesWithAssetId:(NSString * _Nonnull)assetId lastRowKey:(NSString * _Nullable)lastRowKey success:(void (^ _Nullable)(id <IAssetDeviceListResult> _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// get the device list of the asset
/// \param assetId the id of the space which you want to get the device list
///
/// \param statisticsType the statistics type
///
/// \param pageSize the page size
///
/// \param lastRowKey the last row key return by last request, or nil if first request
///
/// \param success the success callback
///
/// \param failure the failure callback
///
- (void)devicesWithAssetId:(NSString * _Nonnull)assetId statisticsType:(NSString * _Nullable)statisticsType pageSize:(NSInteger)pageSize lastRowKey:(NSString * _Nullable)lastRowKey success:(void (^ _Nullable)(id <IAssetDeviceListResult> _Nonnull, NSInteger))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// search device
/// \param assetId the id of the space which you want to get the device list
///
/// \param deviceName the device name
///
/// \param pageSize the page size
///
/// \param lastRowKey the last row key return by last request, or nil if first request
///
/// \param success the success callback
///
/// \param failure the failure callback
///
- (void)searchWithAssetId:(NSString * _Nonnull)assetId deviceName:(NSString * _Nonnull)deviceName pageSize:(NSInteger)pageSize lastRowKey:(NSString * _Nullable)lastRowKey success:(void (^ _Nullable)(id <IAssetDeviceListResult> _Nonnull, NSInteger))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// statistic device count with type
/// \param assetId the id of the space which you want to get the device list
///
/// \param success the success callback
///
/// \param failure the failure callback
///
- (void)statisticsWithAssetId:(NSString * _Nullable)assetId success:(void (^ _Nullable)(NSArray<id <IAssetDeviceStatistics>> * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// get the associated model of the asset
/// \param assetId the id of asset
///
/// \param success the success callback
///
/// \param failure the failure callback
///
- (void)associatedModelWithAssetId:(NSString * _Nonnull)assetId success:(void (^ _Nullable)(id <IAssociatedModel> _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// get the asset message service fot the asset. a new instance return every time
/// \param assetId the asset id
///
///
/// returns:
/// the manager of the asset
- (id <IAssetMessageService> _Nonnull)assetMessageService:(NSString * _Nonnull)assetId SWIFT_WARN_UNUSED_RESULT;
/// get the asset manager fot the asset. a new instance return every time
///
/// returns:
/// the manager of the asset
- (id <IAssetManager> _Nonnull)assetManager SWIFT_WARN_UNUSED_RESULT;
@end


@interface AssetService (SWIFT_EXTENSION(IndustryAssetKit)) <IAssetService>
/// create asset with name
/// \param name the name of the asset to create
///
/// \param parentAssetId the id of the parent asset
///
/// \param success the success callback
///
/// \param failure the failure callback
///
- (void)createWithName:(NSString * _Nonnull)name parentAssetId:(NSString * _Nullable)parentAssetId success:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// update the name of the asset
/// \param assetId the id of the asset to update
///
/// \param name the new name of the asset
///
/// \param success the success callback
///
/// \param failure the failure callback
///
- (void)updateWithAssetId:(NSString * _Nonnull)assetId name:(NSString * _Nonnull)name success:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// remove the asset
/// \param assetId the id of the asset to remove
///
/// \param success the success callback
///
/// \param failure the failure callback
///
- (void)removeWithAssetId:(NSString * _Nonnull)assetId success:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// get the asset detail
/// \param assetId the id of the asset to get
///
/// \param success the success callback
///
/// \param failure the failure callback
///
- (void)assetWithAssetId:(NSString * _Nonnull)assetId success:(void (^ _Nullable)(id <IAsset> _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// get the sub asset list of the asset
/// \param assetId the id of the asset which to get. it means you want to get the top level assets if nil,
///
/// \param success the success callback
///
/// \param failure the failure callback
///
- (void)subAssetsWithAssetId:(NSString * _Nullable)assetId success:(void (^ _Nullable)(NSArray<id <IAsset>> * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// get the device list of the asset
/// \param assetId the id of the asset which you want to get the device list.
///
/// \param lastRowKey the last row key return by last request, or nil if first request
///
/// \param success the success callback
///
/// \param failure the failure callback
///
- (void)devicesWithAssetId:(NSString * _Nonnull)assetId lastRowKey:(NSString * _Nullable)lastRowKey success:(void (^ _Nullable)(id <IAssetDeviceListResult> _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// get the device list of the asset
/// \param assetId the id of the asset which you want to get the device list
///
/// \param statisticsType The statistics type
///
/// \param lastRowKey the last row key return by last request, or nil if first request
///
/// \param success the success callback
///
/// \param failure the failure callback
///
- (void)devicesWithAssetId:(NSString * _Nonnull)assetId statisticsType:(NSString * _Nullable)statisticsType pageSize:(NSInteger)pageSize lastRowKey:(NSString * _Nullable)lastRowKey success:(void (^ _Nullable)(id <IAssetDeviceListResult> _Nonnull, NSInteger))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// statistic device count with type
/// \param assetId the id of the asset which you want to get the device list
///
/// \param success the success callback
///
/// \param failure the failure callback
///
- (void)statisticsWithAssetId:(NSString * _Nullable)assetId success:(void (^ _Nullable)(NSArray<id <IAssetDeviceStatistics>> * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// search device
/// \param assetId the id of the asset which you want to get the device list
///
/// \param deviceName the device name
///
/// \param pageSize the page size
///
/// \param lastRowKey the last row key return by last request, or nil if first request
///
/// \param success the success callback
///
/// \param failure the failure callback
///
- (void)searchWithAssetId:(NSString * _Nonnull)assetId deviceName:(NSString * _Nonnull)deviceName pageSize:(NSInteger)pageSize lastRowKey:(NSString * _Nullable)lastRowKey success:(void (^ _Nullable)(id <IAssetDeviceListResult> _Nonnull, NSInteger))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// get the associated model of the asset
/// \param assetId the id of asset
///
/// \param success the success callback
///
/// \param failure the failure callback
///
- (void)associatedModelWithAssetId:(NSString * _Nonnull)assetId success:(void (^ _Nullable)(id <IAssociatedModel> _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// get the message service fot the asset. a new instance return every time
/// \param asset the asset
///
///
/// returns:
/// the manager of the asset
- (id <IAssetMessageService> _Nonnull)assetMessageService:(NSString * _Nonnull)assetId SWIFT_WARN_UNUSED_RESULT;
/// get the asset manager fot the asset. a new instance return every time
///
/// returns:
/// the manager of the asset
- (id <IAssetManager> _Nonnull)assetManager SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP16IndustryAssetKit6IAsset_")
@protocol IAsset <NSObject>
/// The asset ID.
@property (nonatomic, readonly, copy) NSString * _Nonnull assetId;
/// The name of the asset.
@property (nonatomic, copy) NSString * _Nonnull assetName;
/// The parent asset ID.
@property (nonatomic, readonly, copy) NSString * _Nullable parentAssetId;
/// The permissions on the asset.
/// Valid values:
/// <ul>
///   <li>
///     <code>all</code>: The asset information and associated devices are visible. Device control is supported.
///   </li>
///   <li>
///     <code>read</code>: Only asset information is visible.
///   </li>
/// </ul>
@property (nonatomic, copy) NSString * _Nonnull permission;
/// The number of sub-assets.
@property (nonatomic) NSInteger currentSubAssetNum;
/// The number of devices that belong to the current asset.
@property (nonatomic) NSInteger currentAssetDeviceNum;
/// The asset full path
@property (nonatomic, copy) NSString * _Nonnull userDefinedPath;
@end


SWIFT_PROTOCOL("_TtP16IndustryAssetKit12IAssetDevice_")
@protocol IAssetDevice <NSObject>
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceId;
@property (nonatomic, copy) NSString * _Nonnull deviceName;
@property (nonatomic) BOOL online;
@property (nonatomic, copy) NSString * _Nonnull icon;
@property (nonatomic, copy) NSString * _Nonnull absoluteIconUrl;
@property (nonatomic, readonly, copy) NSString * _Nonnull homeId;
@property (nonatomic, readonly, copy) NSString * _Nonnull permission;
@end


SWIFT_PROTOCOL("_TtP16IndustryAssetKit22IAssetDeviceListResult_")
@protocol IAssetDeviceListResult <NSObject>
@property (nonatomic, copy) NSArray<id <IAssetDevice>> * _Nonnull devices;
@property (nonatomic) BOOL hasMore;
@property (nonatomic, copy) NSString * _Nonnull lastRowKey;
@end


SWIFT_PROTOCOL("_TtP16IndustryAssetKit22IAssetDeviceStatistics_")
@protocol IAssetDeviceStatistics <NSObject>
@property (nonatomic, copy) NSString * _Nonnull typeValue;
@property (nonatomic, copy) NSString * _Nonnull statisticType;
@property (nonatomic) NSInteger total;
@end

@protocol IDevice;

SWIFT_PROTOCOL("_TtP16IndustryAssetKit14IAssetListener_")
@protocol IAssetListener <NSObject>
- (void)asset:(NSString * _Nonnull)assetId didAddDevice:(id <IDevice> _Nonnull)device;
- (void)asset:(NSString * _Nonnull)assetId didRemoveDevice:(NSString * _Nonnull)deviceId;
- (void)asset:(NSString * _Nonnull)assetId deviceInfoUpdate:(id <IDevice> _Nonnull)device;
- (void)asset:(NSString * _Nonnull)assetId device:(id <IDevice> _Nonnull)device dpsUpdate:(NSDictionary<NSString *, id> * _Nonnull)dpsUpdate;
@end

@protocol IAssetManagerListener;

SWIFT_PROTOCOL("_TtP16IndustryAssetKit13IAssetManager_")
@protocol IAssetManager <NSObject>
- (void)registerWithListener:(id <IAssetManagerListener> _Nonnull)listener;
- (void)unregisterWithListener:(id <IAssetManagerListener> _Nonnull)listener;
@end


SWIFT_PROTOCOL("_TtP16IndustryAssetKit21IAssetManagerListener_")
@protocol IAssetManagerListener <NSObject>
- (void)asset:(NSString * _Nonnull)assetId didReceived:(enum AssetEvent)event;
@end


SWIFT_PROTOCOL("_TtP16IndustryAssetKit20IAssetMessageService_")
@protocol IAssetMessageService <NSObject>
@property (nonatomic, readonly, copy) NSString * _Nonnull assetId;
- (void)registerWithListener:(id <IAssetListener> _Nonnull)listener;
- (void)unregisterWithListener:(id <IAssetListener> _Nonnull)listener;
@end



SWIFT_PROTOCOL("_TtP16IndustryAssetKit16IAssociatedModel_")
@protocol IAssociatedModel <NSObject>
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceGroupId;
@property (nonatomic, readonly, copy) NSString * _Nonnull homeId;
@property (nonatomic, readonly, copy) NSString * _Nonnull assetId;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
