// Created By Tuya Umbrella Header Helper

#ifndef TYModuleServices_h
#define TYModuleServices_h
#import "TYOTAGeneralProtocol.h"
#import "TYGroupHandleProtocol.h"
#import "TYSmartGeofenceServiceProtocol.h"
#import "TYMessageCenterProtocol.h"
#import "TYOTAGeneralExternalProtocol.h"
#import "TYThemeManagerProtocol.h"
#import "TYSettingsProtocol.h"
#import "TYPanelProtocol.h"
#import "TYDeviceSyncProtocol.h"
#import "TYDeviceDetailProtocol.h"
#import "TYHelpCenterProtocol.h"
#import "TYSpeechProtocol.h"
#import "TYSmartSceneProtocol.h"
#import "TYSmartGeofenceProtocol.h"
#import "TYSQHomeDataProtocol.h"
#import "TYCameraSettingProtocol.h"
#import "TYSmartHomeDataProtocol.h"
#import "TYLightSceneProtocol.h"
#import "TYCameraProtocol.h"
#import "TYValueAddedServiceProtocol.h"
#import "TYLightSceneBizProtocol.h"
#import "TYSmartSceneBizProtocol.h"
#import "TYSmartHouseIndexProtocol.h"
#import "TYActivatorExternalExtensionProtocol.h"
#import "TYRNCameraProtocol.h"
#import "TYActivatorProtocol.h"
#import "TYSocialShareModel.h"
#import "TYMallProtocol.h"
#import "TYSocialProtocol.h"
#import "TYCameraCloudServiceProtocol.h"
#import "TYFamilyProtocol.h"

#endif