#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
#ifndef THINGIOTNETWORKKIT_SWIFT_H
#define THINGIOTNETWORKKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ThingIoTNetworkKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSString;

SWIFT_CLASS("_TtC18ThingIoTNetworkKit23ThingCustomNotification")
@interface ThingCustomNotification : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tokenInvalid;)
+ (NSString * _Nonnull)tokenInvalid SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull refreshTokenFailed;)
+ (NSString * _Nonnull)refreshTokenFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull didLogin;)
+ (NSString * _Nonnull)didLogin SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull didLogout;)
+ (NSString * _Nonnull)didLogout SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum ThingHTTPMethod : NSInteger;

SWIFT_CLASS("_TtC18ThingIoTNetworkKit16ThingDataRequest")
@interface ThingDataRequest : NSObject
/// The common header for the request
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSDictionary<NSString *, NSString *> * _Nonnull commonHeader;)
+ (NSDictionary<NSString *, NSString *> * _Nonnull)commonHeader SWIFT_WARN_UNUSED_RESULT;
+ (void)setCommonHeader:(NSDictionary<NSString *, NSString *> * _Nonnull)value;
/// The HTTP request method.
@property (nonatomic) enum ThingHTTPMethod method;
/// The API request endpoint string, which doesn’t include the host region and usually starts with a slash. For example, “/v1.0/token/”.
@property (nonatomic, copy) NSString * _Nonnull endpointString;
/// The dictionary sent as the message body of a request, such as for an HTTP POST request.
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull body;
/// A dictionary containing the needed HTTP header fields for a request.
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nonnull header;
/// Create a request model for network request.
/// \param method The HTTP request method.
///
/// \param endpointString The API request endpoint string, which doesn’t include the host region and usually starts with a slash. For example, “/v1.0/token/”.
///
/// \param body The dictionary sent as the message body of a request, such as for an HTTP POST request. Default is an empty dictionary.
///
/// \param header A dictionary containing the needed HTTP header fields for a request. Default is an empty dictionary.
///
- (nonnull instancetype)initWithMethod:(enum ThingHTTPMethod)method endpointString:(NSString * _Nonnull)endpointString body:(NSDictionary<NSString *, id> * _Nonnull)body header:(NSDictionary<NSString *, NSString *> * _Nonnull)header OBJC_DESIGNATED_INITIALIZER;
/// Create a request model for network request.
/// \param method The HTTP request method.
///
/// \param endpointString The API request endpoint string, which doesn’t include the host region and usually starts with a slash. For example, “/v1.0/token/”.
///
/// \param parameters The parameters for the request. If it’s a GET request, the parameters will become part of the URI; otherwise, the parameters will be added to the body field.
///
/// \param header A dictionary containing the needed HTTP header fields for a request. Default is an empty dictionary.
///
- (nonnull instancetype)initWithMethod:(enum ThingHTTPMethod)method endpointString:(NSString * _Nonnull)endpointString parameters:(NSDictionary<NSString *, id> * _Nonnull)parameters header:(NSDictionary<NSString *, NSString *> * _Nonnull)header;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSError;

SWIFT_CLASS("_TtC18ThingIoTNetworkKit10ThingError")
@interface ThingError : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSError * _Nonnull notInitialized;)
+ (NSError * _Nonnull)notInitialized SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSError * _Nonnull parsingDataFailed;)
+ (NSError * _Nonnull)parsingDataFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSError * _Nonnull invalidURL;)
+ (NSError * _Nonnull)invalidURL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSError * _Nonnull refreshTokenFailed;)
+ (NSError * _Nonnull)refreshTokenFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSError * _Nonnull generateQRCodeFailed;)
+ (NSError * _Nonnull)generateQRCodeFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSError * _Nonnull devicePairingTimeout;)
+ (NSError * _Nonnull)devicePairingTimeout SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSError * _Nonnull deviceInitializeFailed;)
+ (NSError * _Nonnull)deviceInitializeFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSError * _Nonnull deviceCommandParsingFailed;)
+ (NSError * _Nonnull)deviceCommandParsingFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSError * _Nonnull deviceCommandInvalid;)
+ (NSError * _Nonnull)deviceCommandInvalid SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSError * _Nonnull deviceCommandUnsupported;)
+ (NSError * _Nonnull)deviceCommandUnsupported SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSError * _Nonnull createDpsGroupInvalid;)
+ (NSError * _Nonnull)createDpsGroupInvalid SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSError * _Nonnull devicePairingFailure;)
+ (NSError * _Nonnull)devicePairingFailure SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)serverErrorWithCode:(NSInteger)code SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// The necessary HTTP request methods for accessing Tuya Cloud.
typedef SWIFT_ENUM(NSInteger, ThingHTTPMethod, open) {
  ThingHTTPMethodGET = 0,
  ThingHTTPMethodPOST = 1,
  ThingHTTPMethodPUT = 2,
  ThingHTTPMethodDELETE = 3,
};

@class NSData;

SWIFT_CLASS("_TtC18ThingIoTNetworkKit12ThingNetwork")
@interface ThingNetwork : NSObject
/// Debug mode, default is false. Verbose log will print into console if opened.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL isDebugMode;)
+ (BOOL)isDebugMode SWIFT_WARN_UNUSED_RESULT;
+ (void)setIsDebugMode:(BOOL)newValue;
/// Initializes the NetworkKit to load necessary information to the memory.
/// \param clientID The value of Access ID/Client ID of your application. You can get the value from the <a href="https://iot.tuya.com/cloud/">Tuya IoT Platform</a>.
///
/// \param clientSecret The value of Access Secret/Client Secret of your application. You can get the value from the <a href="https://iot.tuya.com/cloud/">Tuya IoT Platform</a>.
///
/// \param host The host in which the API request is processed.
///
+ (void)initializeWithClientID:(NSString * _Nonnull)clientID clientSecret:(NSString * _Nonnull)clientSecret;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull host;)
+ (NSString * _Nonnull)host SWIFT_WARN_UNUSED_RESULT;
+ (void)setHost:(NSString * _Nonnull)newValue;
/// Make an HTTP request from a ThingDataRequest.
/// \param request The basic request structure for the network task, which includes HTTP method, HTTP body, HTTP Header, and the endpoint URL.
///
/// \param completion The completion handler to call when the load request is complete.
///
+ (void)request:(ThingDataRequest * _Nonnull)request completion:(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))completion;
/// Make an HTTP request from a ThingDataRequest, and decode the server response to a dictionary. Once the server response is succeed, the data can be retrieved from the dictionary of the completion closure; otherwise check the error in the completion closure.
/// \param request The basic request structure for the network task, which includes HTTP method, HTTP body, HTTP Header, and the endpoint URL.
///
/// \param completion The completion handler to call when the load request is complete. It is recommended to check the dictionary for the response first, if its nil, get the error instead.
///
+ (void)requestAndDecodeToDictionary:(ThingDataRequest * _Nonnull)request completion:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nullable, NSError * _Nullable))completion;
/// Make a HTTP request from a ThingDataRequest, and decode the request result to Bool.
/// \param request The basic request structure for the network task, which includes HTTP method, HTTP body, HTTP Header, and the endpoint URL.
///
/// \param completion The completion handler to call when the load request and decode is complete.
///
+ (void)requestAndDecodeToBool:(ThingDataRequest * _Nonnull)request completion:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18ThingIoTNetworkKit23ThingNetworkEnvironment")
@interface ThingNetworkEnvironment : NSObject
/// The host for Tuya Open API request.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull host;)
+ (NSString * _Nonnull)host SWIFT_WARN_UNUSED_RESULT;
+ (void)setHost:(NSString * _Nonnull)value;
/// The Access ID/Client ID of your application, which can be obtained from <a href="https://iot.tuya.com/cloud/">Tuya IoT Platform</a>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull clientID;)
+ (NSString * _Nonnull)clientID SWIFT_WARN_UNUSED_RESULT;
+ (void)setClientID:(NSString * _Nonnull)value;
/// The Access Secret/Client Secret of your application, which can be obtained from <a href="https://iot.tuya.com/cloud/">Tuya IoT Platform</a>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull clientSecret;)
+ (NSString * _Nonnull)clientSecret SWIFT_WARN_UNUSED_RESULT;
+ (void)setClientSecret:(NSString * _Nonnull)value;
/// The bundle identifier of the application your registered on Tuya IoT Platform. Default value is the bundleIdentifier of your project.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull bundleID;)
+ (NSString * _Nonnull)bundleID SWIFT_WARN_UNUSED_RESULT;
+ (void)setBundleID:(NSString * _Nonnull)value;
/// The language code of the network request which will be added to the header field. It can be retrieved from <code>Locale.current.languageCode</code>. The default value is ‘en’.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull language;)
+ (NSString * _Nonnull)language SWIFT_WARN_UNUSED_RESULT;
+ (void)setLanguage:(NSString * _Nonnull)value;
+ (void)configRefreshTokenWithUrl:(NSString * _Nonnull)url;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSDate;

SWIFT_CLASS("_TtC18ThingIoTNetworkKit13ThingUserInfo")
@interface ThingUserInfo : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable accessToken;)
+ (NSString * _Nullable)accessToken SWIFT_WARN_UNUSED_RESULT;
+ (void)setAccessToken:(NSString * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable refreshToken;)
+ (NSString * _Nullable)refreshToken SWIFT_WARN_UNUSED_RESULT;
+ (void)setRefreshToken:(NSString * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSDate * _Nullable expireTime;)
+ (NSDate * _Nullable)expireTime SWIFT_WARN_UNUSED_RESULT;
+ (void)setExpireTime:(NSDate * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable uid;)
+ (NSString * _Nullable)uid SWIFT_WARN_UNUSED_RESULT;
+ (void)setUid:(NSString * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable mqttUrl;)
+ (NSString * _Nullable)mqttUrl SWIFT_WARN_UNUSED_RESULT;
+ (void)setMqttUrl:(NSString * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable userTopicPrefix;)
+ (NSString * _Nullable)userTopicPrefix SWIFT_WARN_UNUSED_RESULT;
+ (void)setUserTopicPrefix:(NSString * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) NSInteger mqttPort;)
+ (NSInteger)mqttPort SWIFT_WARN_UNUSED_RESULT;
+ (void)setMqttPort:(NSInteger)value;
/// A convenience function for updating the user info.
/// \param accessToken Access token.
///
/// \param refreshToken Refresh token.
///
/// \param expireTime Expire time.
///
/// \param uid User ID.
///
+ (void)updateTokenInfoWithAccessToken:(NSString * _Nonnull)accessToken refreshToken:(NSString * _Nonnull)refreshToken expireTime:(NSDate * _Nonnull)expireTime uid:(NSString * _Nonnull)uid;
/// A convenience function to set all values to nil.
+ (void)emptyTokenInfo;
+ (void)updateMQTTConfigWithUrl:(NSString * _Nonnull)url port:(NSInteger)port userTopicPrefix:(NSString * _Nonnull)userTopicPrefix;
/// Determine if the token is about to expire in a given TimeInterval. If the stored token is nil, a false will be returned.
/// \param range A value that means how many seconds later if the token will expire.
///
///
/// returns:
/// A boolean value that indicates whether the token will expire.
+ (BOOL)tokenNearToExpireIn:(NSTimeInterval)range SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
