//
//  TYCameraSettingProtocol.h
//  TYModuleServices
//
//  Created by lialong on 2020/5/7.
//

#ifndef TYCameraSettingProtocol_h
#define TYCameraSettingProtocol_h

#import <UIKit/UIKit.h>

@protocol TYCameraSettingProtocol <NSObject>

/**
 获取摄像头设置面板
 @param params 摄像头设备的相关参数
 */
- (UIViewController *)settingViewControllerWithDeviceParams:(NSDictionary *)params;

@optional

/**
 Generate config item
 生成自定义配置
 @param tag see developer doc identifiers.
 @param visible whether is visible or not
 @param callBack you can custom jump action
 */
- (id)generateSettingCustomModelWithTag:(NSString *)tag visible:(BOOL)visible callBack:(void(^_Nullable)(void))callBack;

/**
 Config custom setting action and display
 配置设置项是否可见及设置项跳转
 @param items custom items, generated by generateSettingCustomModelWithTag:visible:callBack:
 */
- (void)configCustomItemWithItems:(NSArray<id>*)items;

@end

#endif /* TYCameraSettingProtocol_h */
