#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
#ifndef INDUSTRYDEVICEKIT_SWIFT_H
#define INDUSTRYDEVICEKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="IndustryDeviceKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
typedef SWIFT_ENUM(NSInteger, DeviceError, open) {
  DeviceErrorDeviceModelNilError = 11001,
  DeviceErrorDeviceIdNilError = 11002,
  DeviceErrorDpTypeError = 11003,
  DeviceErrorDpError = 11004,
};

@class NSString;
@protocol IDevice;

SWIFT_PROTOCOL("_TtP17IndustryDeviceKit14IDeviceService_")
@protocol IDeviceService <NSObject>
/// return a industry device with deviceId
/// <ul>
///   <li>
///     Parameters
///     <ul>
///       <li>
///         deviceId: the device id
///       </li>
///     </ul>
///   </li>
/// </ul>
- (id <IDevice> _Nullable)deviceWithDeviceId:(NSString * _Nonnull)deviceId SWIFT_WARN_UNUSED_RESULT;
/// load the device
/// \param deviceId the device id
///
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)load:(NSString * _Nonnull)deviceId success:(void (^ _Nullable)(id <IDevice> _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// rename the device
/// \param deviceId the device id
///
/// \param newName the new name of the device
///
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)rename:(NSString * _Nonnull)deviceId newName:(NSString * _Nonnull)newName success:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// remove the device
/// \param deviceId the device id
///
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)remove:(NSString * _Nonnull)deviceId success:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// reset the device to factory settings
/// \param deviceId the device id
///
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)resetFactory:(NSString * _Nonnull)deviceId success:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// get the sub devices
/// \param deviceId the device id
///
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)subDevices:(NSString * _Nonnull)deviceId success:(void (^ _Nullable)(NSArray<id <IDevice>> * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
@end


SWIFT_CLASS("_TtC17IndustryDeviceKit13DeviceService")
@interface DeviceService : NSObject <IDeviceService>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) DeviceService * _Nonnull shared;)
+ (DeviceService * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(DeviceService * _Nonnull)value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// init a industry device
- (id <IDevice> _Nullable)deviceWithDeviceId:(NSString * _Nonnull)deviceId SWIFT_WARN_UNUSED_RESULT;
/// load the device
/// \param deviceId the device id
///
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)load:(NSString * _Nonnull)deviceId success:(void (^ _Nullable)(id <IDevice> _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// rename the device
/// \param deviceId the device id
///
/// \param newName the new name of the device
///
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)rename:(NSString * _Nonnull)deviceId newName:(NSString * _Nonnull)newName success:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// remove the device
/// \param deviceId the device id
///
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)remove:(NSString * _Nonnull)deviceId success:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// reset the device to factory settings
/// \param deviceId the device id
///
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)resetFactory:(NSString * _Nonnull)deviceId success:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// get the sub devices
/// \param deviceId the device id
///
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)subDevices:(NSString * _Nonnull)deviceId success:(void (^ _Nullable)(NSArray<id <IDevice>> * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
@end

typedef SWIFT_ENUM(NSInteger, DeviceType, open) {
  DeviceTypeUnknown = -1,
  DeviceTypeWifiDevice = 0,
  DeviceTypeBleDevice = 1,
  DeviceTypeGprsDevice = 2,
  DeviceTypeNbDevice = 3,
  DeviceTypeZigbeeGatewayDevice = 4,
  DeviceTypeZigbeeSubDevice = 5,
  DeviceTypeBleMeshSubDevice = 6,
  DeviceTypeInfraredGatewayDevice = 7,
  DeviceTypeInfraredSubDevice = 8,
  DeviceTypeWifiGatewayDevice = 9,
  DeviceTypeWifiSubDevice = 10,
  DeviceTypeSigMeshGatewayDevice = 11,
  DeviceTypeSigMeshSubDevice = 12,
  DeviceTypeBeaconDevice = 13,
  DeviceTypeCat1Device = 14,
};

typedef SWIFT_ENUM(NSInteger, DeviceUpgradeMode, open) {
  DeviceUpgradeModeNormal = 0,
  DeviceUpgradeModePidVersion = 1,
};

typedef SWIFT_ENUM(NSInteger, DeviceUpgradeStatus, open) {
  DeviceUpgradeStatusNormal = 0,
  DeviceUpgradeStatusReady = 1,
  DeviceUpgradeStatusUpgrading = 2,
  DeviceUpgradeStatusSuccess = 3,
  DeviceUpgradeStatusFailure = 4,
  DeviceUpgradeStatusWaitingExectue = 5,
  DeviceUpgradeStatusDownloaded = 6,
  DeviceUpgradeStatusTimeout = 7,
  DeviceUpgradeStatusLocalPrepare = 100,
};


SWIFT_CLASS("_TtC17IndustryDeviceKit2Dp")
@interface Dp : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull dpId;
@property (nonatomic, readonly, strong) id _Nonnull value;
- (nonnull instancetype)initWithDpId:(NSString * _Nonnull)dpId stringValue:(NSString * _Nonnull)stringValue;
- (nonnull instancetype)initWithDpId:(NSString * _Nonnull)dpId intValue:(NSInteger)intValue;
- (nonnull instancetype)initWithDpId:(NSString * _Nonnull)dpId booleanValue:(BOOL)booleanValue;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum DpsPublishMode : NSInteger;

SWIFT_CLASS("_TtC17IndustryDeviceKit9DpCommand")
@interface DpCommand : NSObject
@property (nonatomic, copy) NSArray<Dp *> * _Nonnull dps;
@property (nonatomic) enum DpsPublishMode publishMode;
- (nonnull instancetype)initWithDps:(NSArray<Dp *> * _Nonnull)dps publishMode:(enum DpsPublishMode)publishMode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum DpSchemaType : NSInteger;
@class DpSchemaProperty;

SWIFT_CLASS("_TtC17IndustryDeviceKit8DpSchema")
@interface DpSchema : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nonnull code;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSString * _Nonnull mode;
@property (nonatomic, readonly) enum DpSchemaType type;
@property (nonatomic, readonly, strong) DpSchemaProperty * _Nonnull property;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id code:(NSString * _Nonnull)code name:(NSString * _Nonnull)name mode:(NSString * _Nonnull)mode type:(enum DpSchemaType)type property:(DpSchemaProperty * _Nonnull)property OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17IndustryDeviceKit16DpSchemaProperty")
@interface DpSchemaProperty : NSObject
@property (nonatomic, readonly) enum DpSchemaType type;
@property (nonatomic, readonly, copy) NSString * _Nullable unit;
@property (nonatomic, readonly) double min;
@property (nonatomic, readonly) double max;
@property (nonatomic, readonly) double step;
@property (nonatomic, readonly) NSInteger scale;
@property (nonatomic, readonly) NSInteger maxLen;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable range;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable label;
- (nonnull instancetype)initWithType:(enum DpSchemaType)type unit:(NSString * _Nullable)unit min:(double)min max:(double)max step:(double)step scale:(NSInteger)scale maxLen:(NSInteger)maxLen range:(NSArray<NSString *> * _Nullable)range label:(NSArray<NSString *> * _Nullable)label OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, DpSchemaType, open) {
  DpSchemaTypeEnumeration = 0,
  DpSchemaTypeBool = 1,
  DpSchemaTypeString = 2,
  DpSchemaTypeNumeric = 3,
  DpSchemaTypeBitmap = 4,
  DpSchemaTypeRaw = 5,
  DpSchemaTypeFile = 6,
};

typedef SWIFT_ENUM(NSInteger, DpsPublishMode, open) {
  DpsPublishModeLocal = 0,
  DpsPublishModeCloud = 1,
  DpsPublishModeAuto = 2,
};

@protocol IDeviceBackupNet;
@protocol IDeviceOTA;
@protocol IDeviceDelegate;

SWIFT_PROTOCOL("_TtP17IndustryDeviceKit7IDevice_")
@protocol IDevice <NSObject>
@property (nonatomic, readonly, copy) NSString * _Nullable deviceId;
@property (nonatomic, readonly, copy) NSString * _Nullable uuid;
@property (nonatomic, readonly, copy) NSString * _Nullable name;
@property (nonatomic, readonly, copy) NSString * _Nullable icon;
@property (nonatomic, readonly, copy) NSString * _Nullable productId;
@property (nonatomic, readonly, copy) NSString * _Nullable category;
@property (nonatomic, readonly, copy) NSString * _Nullable timezoneId;
@property (nonatomic, readonly) BOOL isCloudOnline;
@property (nonatomic, readonly) BOOL isLocalOnline;
@property (nonatomic, readonly) BOOL isOnline;
@property (nonatomic, readonly, copy) NSString * _Nullable latitude;
@property (nonatomic, readonly, copy) NSString * _Nullable longitude;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable dps;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, DpSchema *> * _Nullable schemas;
@property (nonatomic, readonly) enum DeviceType deviceType;
@property (nonatomic, readonly, copy) NSString * _Nullable localKey;
@property (nonatomic, readonly) double pv;
@property (nonatomic, readonly, strong) id <IDeviceBackupNet> _Nonnull wifiBackup;
@property (nonatomic, readonly, strong) id <IDeviceOTA> _Nonnull ota;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable meta;
@property (nonatomic, weak) id <IDeviceDelegate> _Nullable delegate;
- (BOOL)isSupport:(NSInteger)attribute SWIFT_WARN_UNUSED_RESULT;
- (void)publishWithDps:(DpCommand * _Nonnull)dps success:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
- (void)getWifiSignalStrengthWithSuccess:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
- (void)subDevicesWithSuccess:(void (^ _Nullable)(NSArray<id <IDevice>> * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
@end

@class WifiBackupModel;

SWIFT_PROTOCOL("_TtP17IndustryDeviceKit16IDeviceBackupNet_")
@protocol IDeviceBackupNet <NSObject>
/// Returns the current Wi-Fi information.
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)getCurrentWifiInfo:(void (^ _Nullable)(NSDictionary<NSString *, id> * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// Returns a list of alternative Wi-Fi networks.
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)getBackupWifiList:(void (^ _Nullable)(NSDictionary<NSString *, id> * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// Sets up a list of alternative networks.
/// \param list A list of alternative Wi-Fi networks. 
///
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)setBackupWifiList:(NSArray<WifiBackupModel *> * _Nonnull)list success:(void (^ _Nullable)(NSDictionary<NSString *, id> * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// Switches to a saved alternative Wi-Fi network.
/// \param hash The hash for the service set identifier (SSID) and password. The value is returned from the device. 
///
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)switchToBackupWifiWithHash:(NSString * _Nonnull)hash success:(void (^ _Nullable)(NSDictionary<NSString *, id> * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// Switches to a new alternative Wi-Fi network.
/// \param ssid The ssid. 
///
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)switchToBackupWifiWithSSID:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password success:(void (^ _Nullable)(NSDictionary<NSString *, id> * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
@end


SWIFT_PROTOCOL("_TtP17IndustryDeviceKit15IDeviceDelegate_")
@protocol IDeviceDelegate <NSObject>
@optional
- (void)deviceInfoUpdatedWithDevice:(id <IDevice> _Nonnull)device;
- (void)deviceDpsUpdatedWithDevice:(id <IDevice> _Nonnull)device;
- (void)deviceOnlineUpdateWithDevice:(id <IDevice> _Nonnull)device;
- (void)deviceRemovedWithDevice:(id <IDevice> _Nonnull)device;
- (void)device:(id <IDevice> _Nonnull)device signalStrength:(NSString * _Nonnull)signalStrength;
- (void)device:(id <IDevice> _Nonnull)device otaStatusChanged:(NSString * _Nonnull)otaStatusChanged;
@end

@protocol IFirmwareUpgradeModel;
@protocol IFirmwareUpgradeStatusModel;

SWIFT_PROTOCOL("_TtP17IndustryDeviceKit10IDeviceOTA_")
@protocol IDeviceOTA <NSObject>
/// Returns firmware upgrade information. ( for general device.)
/// Notice:
/// equal to <code>checkFirmwareUpgradeWithExtraInfo:nil success:success failure:failure</code>
/// @param success Called when the task is finished.
/// @param failure Called when the task is interrupted by an error.
- (void)checkFirmwareUpgrade:(void (^ _Nullable)(NSArray<id <IFirmwareUpgradeModel>> * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// Returns firmware upgrade information. ( for general device and some special device. )
/// Exta info’s ussage:
/// 1. extra info = nil
/// For most general device.
/// 2. extra info =  {“types”: “0,1, ….”, “versions”: “0.0.1,0.0.2, ….”}.
/// For the AP Directly device, which used local lan to upgrade.
/// You can use <code>-getDeviceLocalFirmwareInfo:failure:</code> to get and cached the info <code>type</code> & <code>currentVersion</code>.
/// @param extraInfo Some special device need extra info to check firmwares.
/// @param success Called when the task is finished.
/// @param failure Called when the task is interrupted by an error.
- (void)checkFirmwareUpgradeWithExtraInfo:(NSDictionary<NSString *, NSString *> * _Nonnull)extraInfo success:(void (^ _Nullable)(NSArray<id <IFirmwareUpgradeModel>> * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// Start device firmware upgrade. ( for general device and some special device. )
/// Notice:
/// 1. You can use the TuyaSmartDevice’s delegate ( <code>- device:otaUpdateStatusChanged:</code> ) to receive the status and progress.
/// 2. Please use <code>-checkFirmwareUpgrade:failure:</code> or <code>-checkFirmwareUpgradeWithExtraInfo:success:failure</code> before call this.
/// @param firmwares firmwares from <code>-checkFirmwareUpgrade:failure:</code> or <code>-checkFirmwareUpgradeWithExtraInfo:success:failure</code>
- (void)startFirmwareUpgrade:(NSArray<id <IFirmwareUpgradeModel>> * _Nonnull)firmwares;
/// Confirm continue or not when a upgrading task callback the warning error <code>TYOTAErrorCodeSignalStrengthNotSatisfy </code>.
/// @param isContinue continue or not.
- (void)confirmWarningUpgradeTask:(BOOL)isContinue;
/// Cancel firmware upgrade
/// Notice: it only support for the task status equal to <code>TuyaSmartDeviceUpgradeStatusWaitingExectue</code>
- (void)cancelFirmwareUpgrade:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// Fetch the firmware upgrading task’s status or progress. ( progress maybe 0 )
/// Notice: it only support for the task status equal to <code>TuyaSmartDeviceUpgradeStatusUpgrading</code> or <code>TuyaSmartDeviceUpgradeStatusWaitingExectue</code>
/// @param success Called when the task’s status/progress can provide
/// @param failure Called when the task’s status/progress can’t provide
- (void)getFirmwareUpgradingStatus:(void (^ _Nullable)(id <IFirmwareUpgradeStatusModel> _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// Fetch the device’s local firmware version info. ( now only used for the AP Directly device )
/// Notice:
/// 1. The device need link to app by the LAN.
/// 2. get avaliable infos from the <code>model.type</code> and <code>model.currentVersion</code> properties.
/// @param success Called when the task is finished.
/// @param failure Called when the task is interrupted by an error.
- (void)getDeviceLocalFirmwareInfo:(void (^ _Nullable)(NSArray<id <IFirmwareUpgradeModel>> * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
@end


@class NSNumber;

SWIFT_PROTOCOL("_TtP17IndustryDeviceKit21IFirmwareUpgradeModel_")
@protocol IFirmwareUpgradeModel <NSObject>
/// The update copywriting.
@property (nonatomic, copy) NSString * _Nullable desc;
/// The device type copywriting.
@property (nonatomic, copy) NSString * _Nullable typeDesc;
/// Valid values: <code>0</code>: no later version. <code>1</code>: a later version available. <code>2</code>: updating. <code>5</code>: waiting for the device to wake up.
@property (nonatomic) enum DeviceUpgradeStatus upgradeStatus;
/// The firmware version that is used in the later version.
@property (nonatomic, copy) NSString * _Nullable version;
/// The current firmware version in use.
@property (nonatomic, copy) NSString * _Nullable currentVersion;
/// The update timeout. Unit: seconds.
@property (nonatomic) NSInteger timeout;
/// 0: app update notification. 2: app forced update. 3: update detection.
@property (nonatomic) NSInteger upgradeType;
/// The firmware type.
@property (nonatomic) NSInteger type;
@property (nonatomic) NSInteger devType;
/// The download URL of the update firmware for Bluetooth devices.
@property (nonatomic, copy) NSString * _Nullable url;
/// The firmware MD5 message-digest algorithm.
@property (nonatomic, copy) NSString * _Nullable md5;
/// The size of the firmware package. Unit: bytes.
@property (nonatomic, copy) NSString * _Nullable fileSize;
/// Firmware sign.
@property (nonatomic, copy) NSString * _Nullable sign;
/// The last update time of the DP.
@property (nonatomic) int64_t lastUpgradeTime;
/// The firmware release date.
@property (nonatomic) int64_t firmwareDeployTime;
/// Indicates whether the update device is controllable. <code>1</code> : controllable. <code>0</code> : not controllable.
@property (nonatomic) BOOL controlType;
/// The description of waiting for device wake-up. The low-power non-keep-alive device is in the state of “waiting for device wake-up” before an update.
@property (nonatomic, copy) NSString * _Nullable waitingDesc;
/// The notification text in the firmware update.
@property (nonatomic, copy) NSString * _Nullable upgradingDesc;
/// if the device has the ability to upgrade.can not upgrade like low power. It will be nil when device has not dp check.
@property (nonatomic, strong) NSNumber * _Nullable canUpgrade;
/// the remind when device can not upgrade.Value can be nil.
@property (nonatomic, copy) NSString * _Nullable remind;
/// the firmware sign hmac
@property (nonatomic, copy) NSString * _Nullable hmac;
/// the firmware support differential packet or not
@property (nonatomic) BOOL diffOta;
/// The firmware’s local file path for upgrade used lan way.
@property (nonatomic, copy) NSString * _Nullable filePath;
/// The firmware upgrade mode. (normal upgrade, pid version upgrade, … )
@property (nonatomic) enum DeviceUpgradeMode upgradeMode;
@end

@class NSError;

SWIFT_PROTOCOL("_TtP17IndustryDeviceKit27IFirmwareUpgradeStatusModel_")
@protocol IFirmwareUpgradeStatusModel <NSObject>
/// The firmware update status.
@property (nonatomic) enum DeviceUpgradeStatus upgradeStatus;
/// The firmware type.
@property (nonatomic) NSInteger type;
/// The firmware update description.
@property (nonatomic, copy) NSString * _Nullable statusText;
/// The title of the firmware update description.
@property (nonatomic, copy) NSString * _Nullable statusTitle;
/// The group ota’s task id. When single device update, its value is <= 0.
@property (nonatomic) NSInteger groupId;
/// The firmware update progress. ( sometime can be -1, please ignore when < 0. )
@property (nonatomic) NSInteger progress;
/// The upgrade mode (normal, pid version, … etc)
@property (nonatomic) enum DeviceUpgradeMode upgradeMode;
/// The firmware update error info.
@property (nonatomic, strong) NSError * _Nullable error;
@end


@interface NSError (SWIFT_EXTENSION(IndustryDeviceKit))
+ (NSError * _Nonnull)deviceModelNilError:(NSString * _Nullable)des SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)deviceIdNilError:(NSString * _Nullable)des SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)dpTypeError:(NSString * _Nullable)des SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)dpError:(NSString * _Nullable)des SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC17IndustryDeviceKit15WifiBackupModel")
@interface WifiBackupModel : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull ssid;
@property (nonatomic, readonly, copy) NSString * _Nonnull hValue;
@property (nonatomic, readonly, copy) NSString * _Nonnull password;
- (nonnull instancetype)initWithSsid:(NSString * _Nonnull)ssid hValue:(NSString * _Nonnull)hValue password:(NSString * _Nonnull)password OBJC_DESIGNATED_INITIALIZER;
+ (NSString * _Nonnull)base64HashValue:(NSString * _Nonnull)localKey ssid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
#ifndef INDUSTRYDEVICEKIT_SWIFT_H
#define INDUSTRYDEVICEKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="IndustryDeviceKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
typedef SWIFT_ENUM(NSInteger, DeviceError, open) {
  DeviceErrorDeviceModelNilError = 11001,
  DeviceErrorDeviceIdNilError = 11002,
  DeviceErrorDpTypeError = 11003,
  DeviceErrorDpError = 11004,
};

@class NSString;
@protocol IDevice;

SWIFT_PROTOCOL("_TtP17IndustryDeviceKit14IDeviceService_")
@protocol IDeviceService <NSObject>
/// return a industry device with deviceId
/// <ul>
///   <li>
///     Parameters
///     <ul>
///       <li>
///         deviceId: the device id
///       </li>
///     </ul>
///   </li>
/// </ul>
- (id <IDevice> _Nullable)deviceWithDeviceId:(NSString * _Nonnull)deviceId SWIFT_WARN_UNUSED_RESULT;
/// load the device
/// \param deviceId the device id
///
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)load:(NSString * _Nonnull)deviceId success:(void (^ _Nullable)(id <IDevice> _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// rename the device
/// \param deviceId the device id
///
/// \param newName the new name of the device
///
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)rename:(NSString * _Nonnull)deviceId newName:(NSString * _Nonnull)newName success:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// remove the device
/// \param deviceId the device id
///
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)remove:(NSString * _Nonnull)deviceId success:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// reset the device to factory settings
/// \param deviceId the device id
///
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)resetFactory:(NSString * _Nonnull)deviceId success:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// get the sub devices
/// \param deviceId the device id
///
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)subDevices:(NSString * _Nonnull)deviceId success:(void (^ _Nullable)(NSArray<id <IDevice>> * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
@end


SWIFT_CLASS("_TtC17IndustryDeviceKit13DeviceService")
@interface DeviceService : NSObject <IDeviceService>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) DeviceService * _Nonnull shared;)
+ (DeviceService * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(DeviceService * _Nonnull)value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// init a industry device
- (id <IDevice> _Nullable)deviceWithDeviceId:(NSString * _Nonnull)deviceId SWIFT_WARN_UNUSED_RESULT;
/// load the device
/// \param deviceId the device id
///
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)load:(NSString * _Nonnull)deviceId success:(void (^ _Nullable)(id <IDevice> _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// rename the device
/// \param deviceId the device id
///
/// \param newName the new name of the device
///
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)rename:(NSString * _Nonnull)deviceId newName:(NSString * _Nonnull)newName success:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// remove the device
/// \param deviceId the device id
///
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)remove:(NSString * _Nonnull)deviceId success:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// reset the device to factory settings
/// \param deviceId the device id
///
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)resetFactory:(NSString * _Nonnull)deviceId success:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// get the sub devices
/// \param deviceId the device id
///
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)subDevices:(NSString * _Nonnull)deviceId success:(void (^ _Nullable)(NSArray<id <IDevice>> * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
@end

typedef SWIFT_ENUM(NSInteger, DeviceType, open) {
  DeviceTypeUnknown = -1,
  DeviceTypeWifiDevice = 0,
  DeviceTypeBleDevice = 1,
  DeviceTypeGprsDevice = 2,
  DeviceTypeNbDevice = 3,
  DeviceTypeZigbeeGatewayDevice = 4,
  DeviceTypeZigbeeSubDevice = 5,
  DeviceTypeBleMeshSubDevice = 6,
  DeviceTypeInfraredGatewayDevice = 7,
  DeviceTypeInfraredSubDevice = 8,
  DeviceTypeWifiGatewayDevice = 9,
  DeviceTypeWifiSubDevice = 10,
  DeviceTypeSigMeshGatewayDevice = 11,
  DeviceTypeSigMeshSubDevice = 12,
  DeviceTypeBeaconDevice = 13,
  DeviceTypeCat1Device = 14,
};

typedef SWIFT_ENUM(NSInteger, DeviceUpgradeMode, open) {
  DeviceUpgradeModeNormal = 0,
  DeviceUpgradeModePidVersion = 1,
};

typedef SWIFT_ENUM(NSInteger, DeviceUpgradeStatus, open) {
  DeviceUpgradeStatusNormal = 0,
  DeviceUpgradeStatusReady = 1,
  DeviceUpgradeStatusUpgrading = 2,
  DeviceUpgradeStatusSuccess = 3,
  DeviceUpgradeStatusFailure = 4,
  DeviceUpgradeStatusWaitingExectue = 5,
  DeviceUpgradeStatusDownloaded = 6,
  DeviceUpgradeStatusTimeout = 7,
  DeviceUpgradeStatusLocalPrepare = 100,
};


SWIFT_CLASS("_TtC17IndustryDeviceKit2Dp")
@interface Dp : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull dpId;
@property (nonatomic, readonly, strong) id _Nonnull value;
- (nonnull instancetype)initWithDpId:(NSString * _Nonnull)dpId stringValue:(NSString * _Nonnull)stringValue;
- (nonnull instancetype)initWithDpId:(NSString * _Nonnull)dpId intValue:(NSInteger)intValue;
- (nonnull instancetype)initWithDpId:(NSString * _Nonnull)dpId booleanValue:(BOOL)booleanValue;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum DpsPublishMode : NSInteger;

SWIFT_CLASS("_TtC17IndustryDeviceKit9DpCommand")
@interface DpCommand : NSObject
@property (nonatomic, copy) NSArray<Dp *> * _Nonnull dps;
@property (nonatomic) enum DpsPublishMode publishMode;
- (nonnull instancetype)initWithDps:(NSArray<Dp *> * _Nonnull)dps publishMode:(enum DpsPublishMode)publishMode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum DpSchemaType : NSInteger;
@class DpSchemaProperty;

SWIFT_CLASS("_TtC17IndustryDeviceKit8DpSchema")
@interface DpSchema : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nonnull code;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSString * _Nonnull mode;
@property (nonatomic, readonly) enum DpSchemaType type;
@property (nonatomic, readonly, strong) DpSchemaProperty * _Nonnull property;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id code:(NSString * _Nonnull)code name:(NSString * _Nonnull)name mode:(NSString * _Nonnull)mode type:(enum DpSchemaType)type property:(DpSchemaProperty * _Nonnull)property OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17IndustryDeviceKit16DpSchemaProperty")
@interface DpSchemaProperty : NSObject
@property (nonatomic, readonly) enum DpSchemaType type;
@property (nonatomic, readonly, copy) NSString * _Nullable unit;
@property (nonatomic, readonly) double min;
@property (nonatomic, readonly) double max;
@property (nonatomic, readonly) double step;
@property (nonatomic, readonly) NSInteger scale;
@property (nonatomic, readonly) NSInteger maxLen;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable range;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable label;
- (nonnull instancetype)initWithType:(enum DpSchemaType)type unit:(NSString * _Nullable)unit min:(double)min max:(double)max step:(double)step scale:(NSInteger)scale maxLen:(NSInteger)maxLen range:(NSArray<NSString *> * _Nullable)range label:(NSArray<NSString *> * _Nullable)label OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, DpSchemaType, open) {
  DpSchemaTypeEnumeration = 0,
  DpSchemaTypeBool = 1,
  DpSchemaTypeString = 2,
  DpSchemaTypeNumeric = 3,
  DpSchemaTypeBitmap = 4,
  DpSchemaTypeRaw = 5,
  DpSchemaTypeFile = 6,
};

typedef SWIFT_ENUM(NSInteger, DpsPublishMode, open) {
  DpsPublishModeLocal = 0,
  DpsPublishModeCloud = 1,
  DpsPublishModeAuto = 2,
};

@protocol IDeviceBackupNet;
@protocol IDeviceOTA;
@protocol IDeviceDelegate;

SWIFT_PROTOCOL("_TtP17IndustryDeviceKit7IDevice_")
@protocol IDevice <NSObject>
@property (nonatomic, readonly, copy) NSString * _Nullable deviceId;
@property (nonatomic, readonly, copy) NSString * _Nullable uuid;
@property (nonatomic, readonly, copy) NSString * _Nullable name;
@property (nonatomic, readonly, copy) NSString * _Nullable icon;
@property (nonatomic, readonly, copy) NSString * _Nullable productId;
@property (nonatomic, readonly, copy) NSString * _Nullable category;
@property (nonatomic, readonly, copy) NSString * _Nullable timezoneId;
@property (nonatomic, readonly) BOOL isCloudOnline;
@property (nonatomic, readonly) BOOL isLocalOnline;
@property (nonatomic, readonly) BOOL isOnline;
@property (nonatomic, readonly, copy) NSString * _Nullable latitude;
@property (nonatomic, readonly, copy) NSString * _Nullable longitude;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable dps;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, DpSchema *> * _Nullable schemas;
@property (nonatomic, readonly) enum DeviceType deviceType;
@property (nonatomic, readonly, copy) NSString * _Nullable localKey;
@property (nonatomic, readonly) double pv;
@property (nonatomic, readonly, strong) id <IDeviceBackupNet> _Nonnull wifiBackup;
@property (nonatomic, readonly, strong) id <IDeviceOTA> _Nonnull ota;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable meta;
@property (nonatomic, weak) id <IDeviceDelegate> _Nullable delegate;
- (BOOL)isSupport:(NSInteger)attribute SWIFT_WARN_UNUSED_RESULT;
- (void)publishWithDps:(DpCommand * _Nonnull)dps success:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
- (void)getWifiSignalStrengthWithSuccess:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
- (void)subDevicesWithSuccess:(void (^ _Nullable)(NSArray<id <IDevice>> * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
@end

@class WifiBackupModel;

SWIFT_PROTOCOL("_TtP17IndustryDeviceKit16IDeviceBackupNet_")
@protocol IDeviceBackupNet <NSObject>
/// Returns the current Wi-Fi information.
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)getCurrentWifiInfo:(void (^ _Nullable)(NSDictionary<NSString *, id> * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// Returns a list of alternative Wi-Fi networks.
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)getBackupWifiList:(void (^ _Nullable)(NSDictionary<NSString *, id> * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// Sets up a list of alternative networks.
/// \param list A list of alternative Wi-Fi networks. 
///
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)setBackupWifiList:(NSArray<WifiBackupModel *> * _Nonnull)list success:(void (^ _Nullable)(NSDictionary<NSString *, id> * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// Switches to a saved alternative Wi-Fi network.
/// \param hash The hash for the service set identifier (SSID) and password. The value is returned from the device. 
///
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)switchToBackupWifiWithHash:(NSString * _Nonnull)hash success:(void (^ _Nullable)(NSDictionary<NSString *, id> * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// Switches to a new alternative Wi-Fi network.
/// \param ssid The ssid. 
///
/// \param success callback when success
///
/// \param failure callback when failure
///
- (void)switchToBackupWifiWithSSID:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password success:(void (^ _Nullable)(NSDictionary<NSString *, id> * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
@end


SWIFT_PROTOCOL("_TtP17IndustryDeviceKit15IDeviceDelegate_")
@protocol IDeviceDelegate <NSObject>
@optional
- (void)deviceInfoUpdatedWithDevice:(id <IDevice> _Nonnull)device;
- (void)deviceDpsUpdatedWithDevice:(id <IDevice> _Nonnull)device;
- (void)deviceOnlineUpdateWithDevice:(id <IDevice> _Nonnull)device;
- (void)deviceRemovedWithDevice:(id <IDevice> _Nonnull)device;
- (void)device:(id <IDevice> _Nonnull)device signalStrength:(NSString * _Nonnull)signalStrength;
- (void)device:(id <IDevice> _Nonnull)device otaStatusChanged:(NSString * _Nonnull)otaStatusChanged;
@end

@protocol IFirmwareUpgradeModel;
@protocol IFirmwareUpgradeStatusModel;

SWIFT_PROTOCOL("_TtP17IndustryDeviceKit10IDeviceOTA_")
@protocol IDeviceOTA <NSObject>
/// Returns firmware upgrade information. ( for general device.)
/// Notice:
/// equal to <code>checkFirmwareUpgradeWithExtraInfo:nil success:success failure:failure</code>
/// @param success Called when the task is finished.
/// @param failure Called when the task is interrupted by an error.
- (void)checkFirmwareUpgrade:(void (^ _Nullable)(NSArray<id <IFirmwareUpgradeModel>> * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// Returns firmware upgrade information. ( for general device and some special device. )
/// Exta info’s ussage:
/// 1. extra info = nil
/// For most general device.
/// 2. extra info =  {“types”: “0,1, ….”, “versions”: “0.0.1,0.0.2, ….”}.
/// For the AP Directly device, which used local lan to upgrade.
/// You can use <code>-getDeviceLocalFirmwareInfo:failure:</code> to get and cached the info <code>type</code> & <code>currentVersion</code>.
/// @param extraInfo Some special device need extra info to check firmwares.
/// @param success Called when the task is finished.
/// @param failure Called when the task is interrupted by an error.
- (void)checkFirmwareUpgradeWithExtraInfo:(NSDictionary<NSString *, NSString *> * _Nonnull)extraInfo success:(void (^ _Nullable)(NSArray<id <IFirmwareUpgradeModel>> * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// Start device firmware upgrade. ( for general device and some special device. )
/// Notice:
/// 1. You can use the TuyaSmartDevice’s delegate ( <code>- device:otaUpdateStatusChanged:</code> ) to receive the status and progress.
/// 2. Please use <code>-checkFirmwareUpgrade:failure:</code> or <code>-checkFirmwareUpgradeWithExtraInfo:success:failure</code> before call this.
/// @param firmwares firmwares from <code>-checkFirmwareUpgrade:failure:</code> or <code>-checkFirmwareUpgradeWithExtraInfo:success:failure</code>
- (void)startFirmwareUpgrade:(NSArray<id <IFirmwareUpgradeModel>> * _Nonnull)firmwares;
/// Confirm continue or not when a upgrading task callback the warning error <code>TYOTAErrorCodeSignalStrengthNotSatisfy </code>.
/// @param isContinue continue or not.
- (void)confirmWarningUpgradeTask:(BOOL)isContinue;
/// Cancel firmware upgrade
/// Notice: it only support for the task status equal to <code>TuyaSmartDeviceUpgradeStatusWaitingExectue</code>
- (void)cancelFirmwareUpgrade:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// Fetch the firmware upgrading task’s status or progress. ( progress maybe 0 )
/// Notice: it only support for the task status equal to <code>TuyaSmartDeviceUpgradeStatusUpgrading</code> or <code>TuyaSmartDeviceUpgradeStatusWaitingExectue</code>
/// @param success Called when the task’s status/progress can provide
/// @param failure Called when the task’s status/progress can’t provide
- (void)getFirmwareUpgradingStatus:(void (^ _Nullable)(id <IFirmwareUpgradeStatusModel> _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
/// Fetch the device’s local firmware version info. ( now only used for the AP Directly device )
/// Notice:
/// 1. The device need link to app by the LAN.
/// 2. get avaliable infos from the <code>model.type</code> and <code>model.currentVersion</code> properties.
/// @param success Called when the task is finished.
/// @param failure Called when the task is interrupted by an error.
- (void)getDeviceLocalFirmwareInfo:(void (^ _Nullable)(NSArray<id <IFirmwareUpgradeModel>> * _Nonnull))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
@end


@class NSNumber;

SWIFT_PROTOCOL("_TtP17IndustryDeviceKit21IFirmwareUpgradeModel_")
@protocol IFirmwareUpgradeModel <NSObject>
/// The update copywriting.
@property (nonatomic, copy) NSString * _Nullable desc;
/// The device type copywriting.
@property (nonatomic, copy) NSString * _Nullable typeDesc;
/// Valid values: <code>0</code>: no later version. <code>1</code>: a later version available. <code>2</code>: updating. <code>5</code>: waiting for the device to wake up.
@property (nonatomic) enum DeviceUpgradeStatus upgradeStatus;
/// The firmware version that is used in the later version.
@property (nonatomic, copy) NSString * _Nullable version;
/// The current firmware version in use.
@property (nonatomic, copy) NSString * _Nullable currentVersion;
/// The update timeout. Unit: seconds.
@property (nonatomic) NSInteger timeout;
/// 0: app update notification. 2: app forced update. 3: update detection.
@property (nonatomic) NSInteger upgradeType;
/// The firmware type.
@property (nonatomic) NSInteger type;
@property (nonatomic) NSInteger devType;
/// The download URL of the update firmware for Bluetooth devices.
@property (nonatomic, copy) NSString * _Nullable url;
/// The firmware MD5 message-digest algorithm.
@property (nonatomic, copy) NSString * _Nullable md5;
/// The size of the firmware package. Unit: bytes.
@property (nonatomic, copy) NSString * _Nullable fileSize;
/// Firmware sign.
@property (nonatomic, copy) NSString * _Nullable sign;
/// The last update time of the DP.
@property (nonatomic) int64_t lastUpgradeTime;
/// The firmware release date.
@property (nonatomic) int64_t firmwareDeployTime;
/// Indicates whether the update device is controllable. <code>1</code> : controllable. <code>0</code> : not controllable.
@property (nonatomic) BOOL controlType;
/// The description of waiting for device wake-up. The low-power non-keep-alive device is in the state of “waiting for device wake-up” before an update.
@property (nonatomic, copy) NSString * _Nullable waitingDesc;
/// The notification text in the firmware update.
@property (nonatomic, copy) NSString * _Nullable upgradingDesc;
/// if the device has the ability to upgrade.can not upgrade like low power. It will be nil when device has not dp check.
@property (nonatomic, strong) NSNumber * _Nullable canUpgrade;
/// the remind when device can not upgrade.Value can be nil.
@property (nonatomic, copy) NSString * _Nullable remind;
/// the firmware sign hmac
@property (nonatomic, copy) NSString * _Nullable hmac;
/// the firmware support differential packet or not
@property (nonatomic) BOOL diffOta;
/// The firmware’s local file path for upgrade used lan way.
@property (nonatomic, copy) NSString * _Nullable filePath;
/// The firmware upgrade mode. (normal upgrade, pid version upgrade, … )
@property (nonatomic) enum DeviceUpgradeMode upgradeMode;
@end

@class NSError;

SWIFT_PROTOCOL("_TtP17IndustryDeviceKit27IFirmwareUpgradeStatusModel_")
@protocol IFirmwareUpgradeStatusModel <NSObject>
/// The firmware update status.
@property (nonatomic) enum DeviceUpgradeStatus upgradeStatus;
/// The firmware type.
@property (nonatomic) NSInteger type;
/// The firmware update description.
@property (nonatomic, copy) NSString * _Nullable statusText;
/// The title of the firmware update description.
@property (nonatomic, copy) NSString * _Nullable statusTitle;
/// The group ota’s task id. When single device update, its value is <= 0.
@property (nonatomic) NSInteger groupId;
/// The firmware update progress. ( sometime can be -1, please ignore when < 0. )
@property (nonatomic) NSInteger progress;
/// The upgrade mode (normal, pid version, … etc)
@property (nonatomic) enum DeviceUpgradeMode upgradeMode;
/// The firmware update error info.
@property (nonatomic, strong) NSError * _Nullable error;
@end


@interface NSError (SWIFT_EXTENSION(IndustryDeviceKit))
+ (NSError * _Nonnull)deviceModelNilError:(NSString * _Nullable)des SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)deviceIdNilError:(NSString * _Nullable)des SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)dpTypeError:(NSString * _Nullable)des SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)dpError:(NSString * _Nullable)des SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC17IndustryDeviceKit15WifiBackupModel")
@interface WifiBackupModel : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull ssid;
@property (nonatomic, readonly, copy) NSString * _Nonnull hValue;
@property (nonatomic, readonly, copy) NSString * _Nonnull password;
- (nonnull instancetype)initWithSsid:(NSString * _Nonnull)ssid hValue:(NSString * _Nonnull)hValue password:(NSString * _Nonnull)password OBJC_DESIGNATED_INITIALIZER;
+ (NSString * _Nonnull)base64HashValue:(NSString * _Nonnull)localKey ssid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
